import { Link } from 'react-router-dom'
import { EmptyState } from '../feedback/EmptyState.jsx'
import { Button } from '../ui/Button.jsx'
import { StatusBadge } from '../ui/StatusBadge.jsx'
import { stableDriveCode } from '../../utils/drive-display.js'

const dateLabel = value => value ? new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }) : 'Recently'
const notificationTone = notification => ({ placement_system: 'border-l-violet-500 bg-violet-50/60', college: 'border-l-sky-500 bg-sky-50/60', company: 'border-l-amber-500 bg-amber-50/60', disciplinary_action: 'border-l-rose-500 bg-rose-50/70' }[notification.source] || 'border-l-violet-400 bg-violet-50/40')
function senderLabel(notification, drive, fallbackCompanyName) { if (notification.source === 'placement_system') return 'System / Placement'; if (notification.source === 'college') return 'Placement Admin / College'; if (notification.source === 'disciplinary_action') return 'Discipline'; return drive?.company?.companyName || fallbackCompanyName || 'Company' }
function driveContext(notification, drive, fallbackCompanyName) { if (!notification.placementDriveId) return ''; const company = drive?.company?.companyName || fallbackCompanyName || 'Company'; const role = drive?.role?.title || 'Placement Drive'; return `${company} • ${role} • ${stableDriveCode(notification.placementDriveId)}` }
function recipientLabel(notification) { if (notification.type === 'admin_to_students') return notification.context?.audience === 'drive_applicants' ? 'Active Drive applicants' : notification.context?.audience === 'eligible_drive' ? 'Eligible Drive Students' : 'Verified Students'; if (notification.type === 'company_to_drive_applicants') return 'Active Drive applicants'; if (notification.type === 'company_to_admin') return 'Placement Admin / College'; if (notification.type === 'admin_to_company') return 'Approved Company'; return notification.context?.audience === 'placement_admin' ? 'Placement Admin / College' : 'Placement recipients' }
function sentDeliverySummary(notification) { const recipientCount = notification.recipientCount ?? 1; const readCount = notification.readCount ?? (notification.isRead ? 1 : 0); return { recipientCount, readCount, unreadCount: notification.unreadCount ?? Math.max(recipientCount - readCount, 0) } }

export function NotificationInbox({ notifications, drives = [], busyId, onMarkRead, driveTo, emptyTitle, emptyDescription, fallbackCompanyName, mode = 'received' }) {
  if (!notifications.length) return <EmptyState title={emptyTitle} description={emptyDescription} />
  const driveById = new Map(drives.map(drive => [String(drive._id), drive])); const sent = mode === 'sent'
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-200/50"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 bg-slate-50/70 px-5 py-4"><div><h2 className="font-extrabold tracking-tight text-slate-950">{sent ? 'Sent history' : 'Inbox'}</h2><p className="mt-0.5 text-xs font-medium text-slate-500">{sent ? 'One entry for each communication action.' : 'Messages and placement updates in context.'}</p></div><span className="rounded-full bg-white px-2.5 py-1 text-xs font-bold text-slate-500 shadow-sm">{notifications.length}</span></div><div className="divide-y divide-slate-100">{notifications.map(notification => { const drive = driveById.get(String(notification.placementDriveId)); const context = driveContext(notification, drive, fallbackCompanyName); const delivery = sent ? sentDeliverySummary(notification) : null; return <article key={notification._id} className={`border-l-4 p-5 transition-colors ${!sent && !notification.isRead ? notificationTone(notification) : 'border-l-transparent bg-white hover:bg-slate-50/55'}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-extrabold tracking-tight text-slate-950">{notification.title}</h3><StatusBadge status="neutral">{sent ? `${delivery.readCount} read · ${delivery.unreadCount} unread` : notification.isRead ? 'Read' : 'Unread'}</StatusBadge></div><p className="mt-2 text-xs font-extrabold uppercase tracking-[0.08em] text-slate-600">{sent ? `To: ${recipientLabel(notification)} · ${delivery.recipientCount} recipient${delivery.recipientCount === 1 ? '' : 's'}` : `From: ${senderLabel(notification, drive, fallbackCompanyName)}`}</p><p className="mt-2 text-sm leading-6 text-slate-700">{notification.message}</p>{context && <p className="mt-3 break-words text-sm font-bold text-violet-800">{context}</p>}<p className="mt-3 text-xs font-semibold text-slate-500">{dateLabel(notification.createdAt)}</p></div><div className="flex shrink-0 flex-wrap gap-2 sm:justify-end">{notification.placementDriveId && <Link className="inline-flex min-h-10 items-center justify-center rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm font-bold text-slate-700 shadow-sm transition hover:border-violet-300 hover:bg-violet-50" to={driveTo(notification.placementDriveId)}>View drive</Link>}{!sent && !notification.isRead && <Button variant="quiet" disabled={Boolean(busyId)} onClick={() => onMarkRead(notification)}>{busyId === notification._id ? 'Marking…' : 'Mark read'}</Button>}</div></div></article> })}</div></section>
}
