import { AppError } from '../../errors/app-error.js'
import { User } from '../auth/auth.model.js'
import { Company } from '../companies/company.model.js'
import { Application } from '../applications/application.model.js'
import { PlacementDrive } from '../placement-drives/placement-drive.model.js'
import { PlacementRecord } from '../placements/placement-record.model.js'
import { StudentProfile } from '../students/student.model.js'
import { createPlacementWorkbookExport } from '../recruitment/recruitment-export.service.js'

const active = new Set(['applied', 'screening', 'pending', 'result_pending', 'qualified', 'active'])
const plain = value => value?.toObject ? value.toObject() : value
const companyError = () => new AppError('Only approved Companies can view Company analytics.', { statusCode: 403, errorCode: 'FORBIDDEN' })

async function companyData(companyUserId, { companyModel = Company, placementDriveModel = PlacementDrive, applicationModel = Application, placementRecordModel = PlacementRecord, userModel = User, profileModel = StudentProfile } = {}) {
  const company = await companyModel.findOne({ userId: companyUserId, approvalStatus: 'approved' })
  if (!company) throw companyError()
  const drives = (await placementDriveModel.find({ companyId: company._id }).lean()).map(plain)
  const driveIds = drives.map(drive => drive._id)
  const [applications, records] = await Promise.all([applicationModel.find({ placementDriveId: { $in: driveIds } }).lean(), placementRecordModel.find({ companyId: company._id }).lean()])
  const studentIds = [...new Set(applications.map(app => String(app.studentId)))]
  const [users, profiles] = await Promise.all([userModel.find({ _id: { $in: studentIds }, role: 'student' }).select('_id name email').lean(), profileModel.find({ userId: { $in: studentIds } }).select('userId rollNumber branch cgpa activeBacklogs graduationYear').lean()])
  return { company: plain(company), drives, applications: applications.map(plain), records: records.map(plain), users: users.map(plain), profiles: profiles.map(plain) }
}

function candidateRows(data) {
  const driveById = new Map(data.drives.map(drive => [String(drive._id), drive])); const userById = new Map(data.users.map(user => [String(user._id), user])); const profileById = new Map(data.profiles.map(profile => [String(profile.userId), profile])); const recordByApplication = new Map(data.records.map(record => [String(record.applicationId), record]))
  return data.applications.map(application => { const drive = driveById.get(String(application.placementDriveId)); const user = userById.get(String(application.studentId)); const profile = profileById.get(String(application.studentId)); const record = recordByApplication.get(String(application._id)); const confirmationStatus = record?.verificationState ?? (application.currentStatus === 'selected_pending_confirmation' ? 'selected_report_not_submitted' : ''); return { id: String(application._id), studentId: String(application.studentId), name: user?.name ?? '', email: user?.email ?? '', rollNumber: profile?.rollNumber ?? '', branch: profile?.branch ?? '', cgpa: profile?.cgpa, activeBacklogs: profile?.activeBacklogs, graduationYear: profile?.graduationYear, driveId: String(application.placementDriveId), drive: drive ? { id: String(drive._id), code: drive.driveCode, role: drive.role?.title, phases: drive.phases ?? [] } : null, currentPhase: application.currentPhase, applicationStatus: application.currentStatus, confirmationStatus, outcomeType: record?.outcomeType ?? null, activityAt: application.updatedAt ?? application.appliedAt } })
}

function filterRows(rows, filters) {
  let result = rows; const text = filters.search?.toLowerCase(); if (text) result = result.filter(row => [row.name, row.email, row.rollNumber].some(value => value.toLowerCase().includes(text)))
  for (const [key, value] of Object.entries({ driveId: filters.drive, branch: filters.branch, currentPhase: filters.phase, applicationStatus: filters.status, confirmationStatus: filters.confirmationStatus, outcomeType: filters.outcomeType, graduationYear: filters.graduationYear })) if (value != null && value !== '') result = result.filter(row => String(row[key]) === String(value))
  if (filters.minCpi != null) result = result.filter(row => row.cgpa >= filters.minCpi); if (filters.maxCpi != null) result = result.filter(row => row.cgpa <= filters.maxCpi); if (filters.backlog === 'zero') result = result.filter(row => row.activeBacklogs === 0); if (filters.backlog === 'has_backlog') result = result.filter(row => row.activeBacklogs > 0)
  const field = { cgpa: 'cgpa', branch: 'branch', phase: 'currentPhase', status: 'applicationStatus', activity: 'activityAt' }[filters.sortBy] ?? 'name'; const direction = filters.sortOrder === 'desc' ? -1 : 1
  return [...result].sort((a, b) => (String(a[field] ?? '').localeCompare(String(b[field] ?? '')) * direction) || a.id.localeCompare(b.id))
}

function groups(rows, groupBy) { if (!groupBy) return undefined; const key = groupBy === 'phase' ? row => `Phase ${row.currentPhase}` : groupBy === 'status' ? row => row.applicationStatus : row => row.branch || 'Unspecified'; const map = new Map(); for (const row of rows) { const name = key(row); map.set(name, (map.get(name) ?? 0) + 1) } return [...map.entries()].map(([label, count]) => ({ label, count })).sort((a, b) => a.label.localeCompare(b.label)) }

export async function getCompanyCandidateExplorer(companyUserId, filters, dependencies = {}) { const rows = filterRows(candidateRows(await companyData(companyUserId, dependencies)), filters); const page = filters.page ?? 1; const limit = filters.limit ?? 50; return { records: rows.slice((page - 1) * limit, page * limit), page, limit, totalRecords: rows.length, totalPages: Math.max(1, Math.ceil(rows.length / limit)), groupSummary: groups(rows, filters.groupBy), appliedFilters: filters } }

export async function getCompanyAnalytics(companyUserId, filters = {}, dependencies = {}) {
  const data = await companyData(companyUserId, dependencies); const rows = filterRows(candidateRows(data), filters); const count = status => rows.filter(row => row.applicationStatus === status).length; const activeCandidates = rows.filter(row => active.has(row.applicationStatus)).length; const records = data.records
  const driveAnalytics = data.drives.map(drive => { const driveRows = rows.filter(row => row.driveId === String(drive._id)); const phaseAnalytics = [0, ...(drive.phases ?? []).map(phase => phase.phaseNumber)].map(phaseNumber => { const phaseRows = driveRows.filter(row => row.currentPhase === phaseNumber || data.applications.find(app => String(app._id) === row.id)?.phaseHistory?.some(event => event.phase === phaseNumber)); const histories = data.applications.filter(app => String(app.placementDriveId) === String(drive._id)).flatMap(app => app.phaseHistory ?? []).filter(event => event.phase === phaseNumber); return { phaseNumber, title: phaseNumber === 0 ? 'Phase 0' : drive.phases?.find(phase => phase.phaseNumber === phaseNumber)?.title ?? `Phase ${phaseNumber}`, entered: phaseRows.length, current: driveRows.filter(row => row.currentPhase === phaseNumber && active.has(row.applicationStatus)).length, advanced: histories.filter(event => event.event === 'advanced').length, rejected: histories.filter(event => event.status === 'rejected').length, absent: histories.filter(event => event.status === 'absent').length, withdrawn: driveRows.filter(row => row.currentPhase === phaseNumber && row.applicationStatus === 'withdrawn').length } }); return { id: String(drive._id), role: drive.role?.title, lifecycleStatus: drive.lifecycleStatus, applicantCount: driveRows.length, activeCandidates: driveRows.filter(row => active.has(row.applicationStatus)).length, provisionalSelected: driveRows.filter(row => row.applicationStatus === 'selected_pending_confirmation').length, confirmationPending: driveRows.filter(row => row.confirmationStatus === 'pending_admin_verification').length, confirmed: driveRows.filter(row => row.confirmationStatus === 'confirmed').length, phaseAnalytics } })
  return { kpis: { totalDrives: data.drives.length, activeDrives: data.drives.filter(drive => drive.lifecycleStatus === 'published').length, completedDrives: data.drives.filter(drive => drive.lifecycleStatus === 'completed').length, totalApplications: rows.length, activeCandidates, provisionalSelected: count('selected_pending_confirmation'), offersReceived: rows.filter(row => ['pending_admin_verification', 'confirmed'].includes(row.confirmationStatus)).length, confirmationPending: rows.filter(row => row.confirmationStatus === 'pending_admin_verification').length, confirmedOffers: rows.filter(row => row.confirmationStatus === 'confirmed').length, confirmedPlacements: rows.filter(row => row.confirmationStatus === 'confirmed').length, withdrawn: count('withdrawn'), rejected: count('rejected'), absent: count('absent') }, drives: driveAnalytics }
}

export async function exportCompanyCandidateExplorer(companyUserId, filters, dependencies = {}) { const data = await companyData(companyUserId, dependencies); const matching = filterRows(candidateRows(data), filters); const rows = filters.exportMode === 'current_view' ? matching.slice(((filters.page ?? 1) - 1) * (filters.limit ?? 50), (filters.page ?? 1) * (filters.limit ?? 50)) : matching; const columns = [{ header: 'Name', key: 'name', width: 26 }, { header: 'Roll Number', key: 'roll', width: 18 }, { header: 'Email', key: 'email', width: 30 }, { header: 'Branch', key: 'branch', width: 18 }, { header: 'CPI', key: 'cgpa', width: 10 }, { header: 'Drive', key: 'drive', width: 28 }, { header: 'Current Phase', key: 'phase', width: 16 }, { header: 'Application Status', key: 'status', width: 28 }, { header: 'Confirmation Status', key: 'confirmation', width: 25 }, { header: 'Outcome', key: 'outcome', width: 20 }]; const exportRows = rows.map(row => [row.name, row.rollNumber, row.email, row.branch, row.cgpa ?? '', row.drive?.role ?? '', row.currentPhase, row.applicationStatus, row.confirmationStatus, row.outcomeType ?? '']); return { buffer: await createPlacementWorkbookExport({ title: 'Company Candidate Explorer', columns, rows: exportRows, sheetName: 'Candidates', filterSummary: Object.entries(filters).filter(([key, value]) => value !== '' && !['page', 'limit', 'exportMode'].includes(key)).map(([key, value]) => `${key}: ${value}`).join(', ') }), filename: 'company-candidates.xlsx', rowCount: exportRows.length }
}
