import assert from 'node:assert/strict'
import test from 'node:test'
import jwt from 'jsonwebtoken'
import { mkdtemp, writeFile, rm } from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
import { env } from '../src/config/env.js'

const ids = { student: '507f1f77bcf86cd799439101', other: '507f1f77bcf86cd799439102', admin: '507f1f77bcf86cd799439103', company: '507f1f77bcf86cd799439104', drive: '507f1f77bcf86cd799439105', application: '507f1f77bcf86cd799439106', record: '507f1f77bcf86cd799439107' }
const token = subject => `Bearer ${jwt.sign({}, env.JWT_SECRET, { subject, expiresIn: '1h' })}`
async function serverFor(t, role, setup = () => {}) { const { app } = await import('../src/app.js'); const { User } = await import('../src/modules/auth/auth.model.js'); setup(t); t.mock.method(User, 'findById', userId => ({ select: async () => ({ _id: userId, role: typeof role === 'function' ? role(userId) : role, isActive: true }) })); const server = app.listen(0); t.after(() => new Promise(resolve => server.close(resolve))); return `http://127.0.0.1:${server.address().port}/api/v1` }

test('Student reporting endpoint accepts only the owner’s provisionally selected application and supports pending update', async t => {
  let record; const url = await serverFor(t, 'student', () => {}); const { Application } = await import('../src/modules/applications/application.model.js'); const { PlacementDrive } = await import('../src/modules/placement-drives/placement-drive.model.js'); const { PlacementRecord } = await import('../src/modules/placements/placement-record.model.js'); const application = { _id: ids.application, studentId: ids.student, placementDriveId: ids.drive, currentStatus: 'selected_pending_confirmation', phaseHistory: [], save: async function () { return this } }; t.mock.method(Application, 'findOne', async query => query.studentId === ids.student ? application : null); t.mock.method(PlacementDrive, 'findOne', async () => ({ _id: ids.drive, companyId: ids.company, role: { title: 'Engineer' } })); t.mock.method(PlacementRecord, 'findOne', async () => record ?? null); t.mock.method(PlacementRecord, 'create', async value => { record = { _id: ids.record, ...value, save: async function () { return this } }; return record });
  const body = { outcomeType: 'full_time', location: 'Pune' }; let response = await fetch(`${url}/students/me/applications/${ids.application}/placement-report`, { method: 'POST', headers: { Authorization: token(ids.student), 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); assert.equal(response.status, 201); response = await fetch(`${url}/students/me/applications/${ids.application}/placement-report`, { method: 'POST', headers: { Authorization: token(ids.student), 'Content-Type': 'application/json' }, body: JSON.stringify({ ...body, location: 'Bengaluru' }) }); assert.equal(response.status, 201); assert.equal(record.location, 'Bengaluru')
})

test('non-Admin users cannot use Admin placement outcome endpoints', async t => { const url = await serverFor(t, 'student'); const response = await fetch(`${url}/admin/placement-outcomes`, { headers: { Authorization: token(ids.student) } }); assert.equal(response.status, 403) })
test('invalid report payload and stale application ids are rejected safely', async t => { const url = await serverFor(t, 'student'); const invalid = await fetch(`${url}/students/me/applications/${ids.application}/placement-report`, { method: 'POST', headers: { Authorization: token(ids.student), 'Content-Type': 'application/json' }, body: JSON.stringify({ outcomeType: 'bad' }) }); assert.equal(invalid.status, 422) })

test('Student proof upload uses the real PDF route and proof reads remain owner/Admin scoped', async t => {
  const url = await serverFor(t, 'student'); const { PlacementRecord } = await import('../src/modules/placements/placement-record.model.js'); const record = { _id: ids.record, applicationId: ids.application, studentId: ids.student, verificationState: 'pending_admin_verification', proof: [], history: [], save: async function () { return this } }; t.mock.method(PlacementRecord, 'findOne', async query => query.studentId && query.studentId !== ids.student ? null : record)
  const form = new FormData(); form.append('document', new Blob(['%PDF-1.4\nproof'], { type: 'application/pdf' }), 'offer.pdf'); let response = await fetch(`${url}/students/me/applications/${ids.application}/placement-proof`, { method: 'POST', headers: { Authorization: token(ids.student) }, body: form }); assert.equal(response.status, 201); assert.equal(record.proof.length, 1); assert.equal(JSON.stringify(await response.json()).includes('storagePath'), false)
  response = await fetch(`${url}/students/me/placement-outcomes/${ids.record}/proofs/0/download`, { headers: { Authorization: token(ids.other) } }); assert.equal(response.status, 404)
})

test('non-PDF proof is rejected', async t => { const url = await serverFor(t, 'student'); const form = new FormData(); form.append('document', new Blob(['not a PDF'], { type: 'text/plain' }), 'offer.txt'); const upload = await fetch(`${url}/students/me/applications/${ids.application}/placement-proof`, { method: 'POST', headers: { Authorization: token(ids.student) }, body: form }); assert.equal(upload.status, 422) })
test('Company users cannot access Student proof routes', async t => { const url = await serverFor(t, 'company'); const proof = await fetch(`${url}/students/me/placement-outcomes/${ids.record}/proofs/0/download`, { headers: { Authorization: token(ids.student) } }); assert.equal(proof.status, 403) })

test('Admin endpoints list pending outcomes and enforce role access', async t => {
  const url = await serverFor(t, 'placement_admin'); const { PlacementRecord } = await import('../src/modules/placements/placement-record.model.js'); const query = { sort: () => ({ populate: () => ({ populate: async () => [{ _id: ids.record, verificationState: 'pending_admin_verification', proof: [] }] }) }) }; t.mock.method(PlacementRecord, 'find', () => query); const response = await fetch(`${url}/admin/placement-outcomes?state=pending_admin_verification`, { headers: { Authorization: token(ids.admin) } }); assert.equal(response.status, 200); assert.equal((await response.json()).data.length, 1)
})

test('Admin confirmation route finalizes source, closes other journeys once, and repairs a partial confirmed state', async t => {
  const url = await serverFor(t, 'placement_admin'); const { PlacementRecord } = await import('../src/modules/placements/placement-record.model.js'); const { Application } = await import('../src/modules/applications/application.model.js'); const { Notification } = await import('../src/modules/notifications/notification.model.js'); const source = { _id: ids.application, studentId: ids.student, placementDriveId: ids.drive, currentPhase: 2, currentStatus: 'selected_pending_confirmation', phaseHistory: [], save: async function () { return this } }; const other = { _id: '507f1f77bcf86cd799439199', studentId: ids.student, placementDriveId: '507f1f77bcf86cd799439198', currentPhase: 1, currentStatus: 'active', phaseHistory: [], save: async function () { return this } }; const record = { _id: ids.record, studentId: ids.student, applicationId: ids.application, placementDriveId: ids.drive, companyId: ids.company, outcomeType: 'full_time', verificationState: 'pending_admin_verification', history: [], save: async function () { return this } }; const sent = []; t.mock.method(PlacementRecord, 'findOne', async () => record); t.mock.method(Application, 'findOne', async () => source); t.mock.method(Application, 'find', async () => other.currentStatus === 'active' ? [other] : []); t.mock.method(Notification, 'create', async values => { sent.push(...values); return values });
  let response = await fetch(`${url}/admin/placement-outcomes/${ids.record}/confirm`, { method: 'PATCH', headers: { Authorization: token(ids.admin), 'Content-Type': 'application/json' }, body: JSON.stringify({ reason: 'Verified' }) }); assert.equal(response.status, 200); assert.deepEqual([record.verificationState, source.currentStatus, other.currentStatus], ['confirmed', 'placement_confirmed', 'closed_placed_elsewhere']); assert.equal(sent.length, 2)
  response = await fetch(`${url}/admin/placement-outcomes/${ids.record}/confirm`, { method: 'PATCH', headers: { Authorization: token(ids.admin), 'Content-Type': 'application/json' }, body: JSON.stringify({ reason: 'Verified' }) }); assert.equal(response.status, 200); assert.equal(sent.length, 2); assert.equal(other.phaseHistory.length, 1)
  source.currentStatus = 'selected_pending_confirmation'; const repair = await fetch(`${url}/admin/placement-outcomes/${ids.record}/confirm`, { method: 'PATCH', headers: { Authorization: token(ids.admin), 'Content-Type': 'application/json' }, body: JSON.stringify({ reason: 'Verified' }) }); assert.equal(repair.status, 200); assert.equal(source.currentStatus, 'placement_confirmed'); assert.equal(source.phaseHistory.length, 1)
})

test('Admin reject and revoke routes preserve outcome history', async t => {
  const url = await serverFor(t, 'placement_admin'); const { PlacementRecord } = await import('../src/modules/placements/placement-record.model.js'); const record = { _id: ids.record, verificationState: 'pending_admin_verification', history: [], save: async function () { return this } }; t.mock.method(PlacementRecord, 'findOne', async () => record)
  let response = await fetch(`${url}/admin/placement-outcomes/${ids.record}/decision`, { method: 'PATCH', headers: { Authorization: token(ids.admin), 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'reject', reason: 'Proof needs correction' }) }); assert.equal(response.status, 200); assert.equal(record.verificationState, 'rejected'); assert.equal(record.history.at(-1).event, 'admin_rejected')
  record.verificationState = 'confirmed'; response = await fetch(`${url}/admin/placement-outcomes/${ids.record}/decision`, { method: 'PATCH', headers: { Authorization: token(ids.admin), 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'revoke', reason: 'Offer withdrawn' }) }); assert.equal(response.status, 200); assert.equal(record.verificationState, 'revoked'); assert.equal(record.history.at(-1).event, 'admin_revoked')
})

test('Admin can download a proof while non-Admins are denied the Admin proof route', async t => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'placement-proof-')); const proofPath = path.join(directory, 'offer.pdf'); await writeFile(proofPath, '%PDF-1.4\nproof'); t.after(() => rm(directory, { recursive: true, force: true })); const url = await serverFor(t, 'placement_admin'); const { PlacementRecord } = await import('../src/modules/placements/placement-record.model.js'); t.mock.method(PlacementRecord, 'findOne', async () => ({ _id: ids.record, proof: [{ originalName: 'offer.pdf', storagePath: proofPath }] })); const response = await fetch(`${url}/admin/placement-outcomes/${ids.record}/proofs/0/download`, { headers: { Authorization: token(ids.admin) } }); assert.equal(response.status, 200); assert.equal((await response.text()).includes('storagePath'), false)
})

test('Company unselect route restores a provisional final-phase candidate and invalidates its pending report', async t => {
  const url = await serverFor(t, 'company'); const { Company } = await import('../src/modules/companies/company.model.js'); const { PlacementDrive } = await import('../src/modules/placement-drives/placement-drive.model.js'); const { Application } = await import('../src/modules/applications/application.model.js'); const { PlacementRecord } = await import('../src/modules/placements/placement-record.model.js'); const { Notification } = await import('../src/modules/notifications/notification.model.js'); const application = { _id: ids.application, studentId: ids.student, placementDriveId: ids.drive, currentPhase: 2, currentStatus: 'selected_pending_confirmation', phaseHistory: [{ event: 'provisionally_selected' }] }; const record = { verificationState: 'pending_admin_verification', history: [], save: async function () { return this } }; t.mock.method(Company, 'findOne', async () => ({ _id: ids.company, userId: ids.company, approvalStatus: 'approved' })); t.mock.method(PlacementDrive, 'findOne', async () => ({ _id: ids.drive, companyId: ids.company, proposalStatus: 'approved', lifecycleStatus: 'published', phases: [{ phaseNumber: 1 }, { phaseNumber: 2 }] })); t.mock.method(Application, 'findOne', async () => application); t.mock.method(Application, 'findOneAndUpdate', async (_query, update) => Object.assign(application, update.$set)); t.mock.method(PlacementRecord, 'findOne', async () => record); t.mock.method(Notification, 'create', async values => values); const response = await fetch(`${url}/companies/me/placement-drives/${ids.drive}/recruitment/candidates/${ids.application}/transition`, { method: 'POST', headers: { Authorization: token(ids.company), 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'unselect', reason: 'Offer corrected' }) }); assert.equal(response.status, 200); assert.deepEqual([application.currentPhase, application.currentStatus, record.verificationState], [2, 'active', 'rejected']); assert.equal(application.phaseHistory.at(-1).event, 'unselected')
})

test('Company cannot unselect an Admin-confirmed candidate through the transition route', async t => {
  const url = await serverFor(t, 'company'); const { Company } = await import('../src/modules/companies/company.model.js'); const { PlacementDrive } = await import('../src/modules/placement-drives/placement-drive.model.js'); const { Application } = await import('../src/modules/applications/application.model.js'); const confirmed = { _id: ids.application, studentId: ids.student, placementDriveId: ids.drive, currentPhase: 2, currentStatus: 'placement_confirmed', phaseHistory: [{ event: 'placement_confirmed' }] }; t.mock.method(Company, 'findOne', async () => ({ _id: ids.company, userId: ids.company, approvalStatus: 'approved' })); t.mock.method(PlacementDrive, 'findOne', async () => ({ _id: ids.drive, companyId: ids.company, proposalStatus: 'approved', lifecycleStatus: 'published', phases: [{ phaseNumber: 1 }, { phaseNumber: 2 }] })); t.mock.method(Application, 'findOne', async () => confirmed); const response = await fetch(`${url}/companies/me/placement-drives/${ids.drive}/recruitment/candidates/${ids.application}/transition`, { method: 'POST', headers: { Authorization: token(ids.company), 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'unselect', reason: 'Not permitted' }) }); assert.equal(response.status, 409); assert.equal(confirmed.currentStatus, 'placement_confirmed'); assert.equal(confirmed.phaseHistory.length, 1)
})

test('Company selected-pool route is owner-scoped and returns no proof or Admin-private fields', async t => {
  const { Company } = await import('../src/modules/companies/company.model.js'); const { PlacementDrive } = await import('../src/modules/placement-drives/placement-drive.model.js'); const { Application } = await import('../src/modules/applications/application.model.js'); const { PlacementRecord } = await import('../src/modules/placements/placement-record.model.js'); const { User } = await import('../src/modules/auth/auth.model.js'); const { StudentProfile } = await import('../src/modules/students/student.model.js'); t.mock.method(User, 'findOne', async () => ({ _id: ids.student, name: 'Student' })); const url = await serverFor(t, 'company'); t.mock.method(Company, 'findOne', async query => query.userId === ids.company ? { _id: ids.company, approvalStatus: 'approved' } : null); t.mock.method(PlacementDrive, 'findOne', async query => query.companyId === ids.company ? { _id: ids.drive, companyId: ids.company, proposalStatus: 'approved', lifecycleStatus: 'published', role: { title: 'Engineer' }, phases: [{ phaseNumber: 2 }] } : null); t.mock.method(Application, 'find', () => ({ sort: async () => [{ _id: ids.application, studentId: ids.student, placementDriveId: ids.drive, currentPhase: 2, currentStatus: 'selected_pending_confirmation' }] })); t.mock.method(PlacementRecord, 'find', () => ({ sort: async () => [{ applicationId: ids.application, verificationState: 'pending_admin_verification', outcomeType: 'full_time', notes: 'private', proof: [{ storagePath: '/private/proof.pdf' }], history: [{ note: 'admin only' }] }] })); t.mock.method(StudentProfile, 'findOne', async () => ({ rollNumber: 'R1', branch: 'CSE', cgpa: 8 })); let response = await fetch(`${url}/companies/me/placement-drives/${ids.drive}/recruitment/candidates?status=selected_pending_confirmation`, { headers: { Authorization: token(ids.company) } }); assert.equal(response.status, 200); const payload = await response.json(); assert.equal(payload.data.candidates[0].selection.state, 'confirmation_pending'); assert.equal(payload.data.candidates[0].selection.outcomeType, 'full_time'); assert.equal(JSON.stringify(payload).includes('storagePath'), false); assert.equal(JSON.stringify(payload).includes('private'), false); response = await fetch(`${url}/companies/me/placement-drives/${ids.drive}/recruitment/candidates?status=selected_pending_confirmation`, { headers: { Authorization: token(ids.other) } }); assert.equal(response.status, 403)
})

test('actual Apply route blocks every confirmed placement outcome, including internship', async t => {
  const { StudentProfile } = await import('../src/modules/students/student.model.js'); const { StudentPlacementPolicy, StudentPolicyAcceptance } = await import('../src/modules/student-policy/student-policy.model.js'); const { PlacementRestriction } = await import('../src/modules/applications/placement-restriction.model.js'); const { Company } = await import('../src/modules/companies/company.model.js'); const { PlacementDrive } = await import('../src/modules/placement-drives/placement-drive.model.js'); const { Application } = await import('../src/modules/applications/application.model.js'); const { PlacementRecord } = await import('../src/modules/placements/placement-record.model.js'); const url = await serverFor(t, 'student'); const created = []; let outcome = 'full_time'; const drive = { _id: ids.drive, companyId: ids.company, proposalStatus: 'approved', lifecycleStatus: 'published', eligibility: { allowedBranches: ['CSE'], minimumCgpa: 7, maximumActiveBacklogs: 0, graduationYears: [2027] }, driveDetails: { applicationDeadline: new Date(Date.now() + 86400000) } }; t.mock.method(StudentProfile, 'findOne', async () => ({ userId: ids.student, verificationStatus: 'verified', branch: 'CSE', cgpa: 8, activeBacklogs: 0, graduationYear: 2027 })); t.mock.method(StudentPlacementPolicy, 'findOne', async () => ({ _id: 'policy' })); t.mock.method(StudentPolicyAcceptance, 'findOne', async () => ({ studentId: ids.student })); t.mock.method(PlacementRestriction, 'findOne', async () => null); t.mock.method(Company, 'findOne', async () => ({ _id: ids.company, approvalStatus: 'approved' })); t.mock.method(PlacementDrive, 'findOne', async () => drive); t.mock.method(Application, 'findOne', async () => created[0] ?? null); t.mock.method(Application, 'create', async value => { const app = { _id: 'new', ...value }; created.push(app); return app }); t.mock.method(PlacementRecord, 'findOne', async query => query.outcomeType?.$in?.includes(outcome) ? { verificationState: 'confirmed', outcomeType: outcome } : null);
  for (const type of ['full_time', 'ppo', 'internship_and_ppo', 'internship']) { outcome = type; created.length = 0; const response = await fetch(`${url}/students/me/placement-drives/${ids.drive}/apply`, { method: 'POST', headers: { Authorization: token(ids.student) } }); assert.equal(response.status, 422); assert.equal(created.length, 0) }
})

test('HTTP revoke restores only future Apply eligibility without reopening closed journeys', async t => {
  const { StudentProfile } = await import('../src/modules/students/student.model.js'); const { StudentPlacementPolicy, StudentPolicyAcceptance } = await import('../src/modules/student-policy/student-policy.model.js'); const { PlacementRestriction } = await import('../src/modules/applications/placement-restriction.model.js'); const { PlacementDrive } = await import('../src/modules/placement-drives/placement-drive.model.js'); const { Application } = await import('../src/modules/applications/application.model.js'); const { PlacementRecord } = await import('../src/modules/placements/placement-record.model.js'); const url = await serverFor(t, userId => userId === ids.admin ? 'placement_admin' : 'student'); const created = []; const old = { _id: 'old', currentStatus: 'closed_placed_elsewhere' }; const record = { _id: ids.record, studentId: ids.student, outcomeType: 'full_time', verificationState: 'confirmed', history: [], save: async function () { return this } }; const drive = { _id: ids.drive, proposalStatus: 'approved', lifecycleStatus: 'published', eligibility: { allowedBranches: ['CSE'], minimumCgpa: 7, maximumActiveBacklogs: 0, graduationYears: [2027] }, driveDetails: { applicationDeadline: new Date(Date.now() + 86400000) } }; t.mock.method(StudentProfile, 'findOne', async () => ({ verificationStatus: 'verified', branch: 'CSE', cgpa: 8, activeBacklogs: 0, graduationYear: 2027 })); t.mock.method(StudentPlacementPolicy, 'findOne', async () => ({ _id: 'policy' })); t.mock.method(StudentPolicyAcceptance, 'findOne', async () => ({ studentId: ids.student })); t.mock.method(PlacementRestriction, 'findOne', async () => null); t.mock.method(PlacementDrive, 'findOne', async () => drive); t.mock.method(Application, 'findOne', async () => created[0] ?? null); t.mock.method(Application, 'create', async value => { const app = { _id: 'new', ...value }; created.push(app); return app }); t.mock.method(PlacementRecord, 'findOne', async query => query.outcomeType?.$in ? (record.verificationState === 'confirmed' ? record : null) : record);
  let response = await fetch(`${url}/students/me/placement-drives/${ids.drive}/apply`, { method: 'POST', headers: { Authorization: token(ids.student) } }); assert.equal(response.status, 422); response = await fetch(`${url}/admin/placement-outcomes/${ids.record}/decision`, { method: 'PATCH', headers: { Authorization: token(ids.admin), 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'revoke', reason: 'Offer withdrawn' }) }); assert.equal(response.status, 200); assert.equal(record.verificationState, 'revoked'); response = await fetch(`${url}/students/me/placement-drives/${ids.drive}/apply`, { method: 'POST', headers: { Authorization: token(ids.student) } }); assert.equal(response.status, 201); assert.deepEqual([created.length, old.currentStatus, record.history.at(-1).event], [1, 'closed_placed_elsewhere', 'admin_revoked'])
})
