import assert from 'node:assert/strict'
import test from 'node:test'
import { createOffCampusPlacement } from '../src/modules/placements/placement-record.service.js'

const ids = { admin: '507f1f77bcf86cd799439501', student: '507f1f77bcf86cd799439502', application: '507f1f77bcf86cd799439503' }
const saveable = value => ({ ...value, save: async function () { return this } })
function deps({ outcomeType = 'full_time', duplicate = null } = {}) { const created = []; const app = saveable({ _id: ids.application, studentId: ids.student, currentPhase: 2, currentStatus: 'active', phaseHistory: [] }); return { created, app, values: { studentId: ids.student, employerName: 'Independent Labs', role: 'Engineer', outcomeType, confirmationDate: new Date('2026-10-06'), package: { amount: 1200000, currency: 'INR', period: 'per_annum' } }, dependencies: { userModel: { findOne: () => ({ select: async () => ({ _id: ids.student }) }) }, recordModel: { findOne: async () => duplicate, create: async value => { created.push(value); return value } }, applicationModel: { find: async () => [app] }, notificationService: async () => [] } } }
test('Admin off-campus record is source-authoritative, needs no Company/Drive/Application, and blocks equivalent outcomes', async () => { const fixture = deps(); const result = await createOffCampusPlacement(ids.admin, fixture.values, fixture.dependencies); assert.equal(result.record.placementSource, 'OFF_CAMPUS'); assert.equal(result.record.companyId, undefined); assert.equal(result.record.applicationId, undefined); assert.equal(result.record.verificationState, 'confirmed'); assert.equal(fixture.app.currentStatus, 'closed_placed_elsewhere'); assert.equal(result.closedApplications, 1) })
test('Confirmed internship off-campus record blocks active applications and duplicates are rejected', async () => { const internship = deps({ outcomeType: 'internship' }); await createOffCampusPlacement(ids.admin, internship.values, internship.dependencies); assert.equal(internship.app.currentStatus, 'closed_placed_elsewhere'); const duplicate = deps({ duplicate: { _id: 'existing' } }); await assert.rejects(createOffCampusPlacement(ids.admin, duplicate.values, duplicate.dependencies), error => error.errorCode === 'CONFLICT') })
test('PPO and internship-plus-PPO off-campus records use the same blocking rule', async () => { for (const outcomeType of ['ppo', 'internship_and_ppo']) { const fixture = deps({ outcomeType }); await createOffCampusPlacement(ids.admin, fixture.values, fixture.dependencies); assert.equal(fixture.app.currentStatus, 'closed_placed_elsewhere') } })
