import assert from 'node:assert/strict'
import test from 'node:test'

process.env.MONGO_URI = 'mongodb://127.0.0.1:27017/placementhub-v2-test'
const { exploreStudents } = await import('../src/modules/students/student.service.js')
const lean = values => ({ lean: async () => values })
const users = [{ _id: 's1', name: 'Asha Kumar', email: 'asha@example.test' }, { _id: 's2', name: 'Bharat Singh', email: 'bharat@example.test' }, { _id: 's3', name: 'Cia Das', email: 'cia@example.test' }]
const profiles = [{ userId: 's1', rollNumber: 'IT001', branch: 'IT', graduationYear: 2027, cgpa: 9, activeBacklogs: 0, verificationStatus: 'verified', updatedAt: new Date('2027-03-03') }, { userId: 's2', rollNumber: 'CS002', branch: 'CSE', graduationYear: 2027, cgpa: 8, activeBacklogs: 1, verificationStatus: 'verified', updatedAt: new Date('2027-03-02') }, { userId: 's3', rollNumber: 'IT003', branch: 'IT', graduationYear: 2028, cgpa: 7, activeBacklogs: 0, verificationStatus: 'pending', updatedAt: new Date('2027-03-01') }]
const records = [{ studentId: 's1', companyId: 'c1', outcomeType: 'full_time', verificationState: 'confirmed' }, { studentId: 's2', companyId: 'c1', outcomeType: 'internship', verificationState: 'confirmed' }, { studentId: 's3', companyId: 'c1', outcomeType: 'ppo', verificationState: 'revoked' }]
const applications = [{ studentId: 's1', placementDriveId: 'd1', currentPhase: 3, currentStatus: 'placement_confirmed', updatedAt: new Date('2027-03-04') }, { studentId: 's2', placementDriveId: 'd1', currentPhase: 2, currentStatus: 'active', updatedAt: new Date('2027-03-05') }]
const deps = { userModel: { find: () => ({ select: () => lean(users) }) }, profileModel: { find: () => lean(profiles) }, recordModel: { find: query => lean(records.filter(record => record.verificationState === query.verificationState)) }, applicationModel: { find: () => lean(applications) }, driveModel: { find: () => ({ select: () => lean([]) }) }, companyModel: { find: () => ({ select: () => lean([{ _id: 'c1', companyName: 'Acme' }]) }) }, institutionService: async () => ({ collegeEligibility: { minimumCgpa: 7, maximumActiveBacklogs: 0, graduationYears: [2027, 2028] } }) }

test('Explorer search is case-insensitive across name, roll, and email', async () => { for (const query of ['asha', 'it001', 'BHARAT@']) { const result = await exploreStudents({ search: query, page: 1, limit: 50 }, deps); assert.equal(result.totalRecords, 1) } })
test('Explorer filters treat confirmed internships as placed while preserving outcome filtering', async () => { assert.equal((await exploreStudents({ branch: 'IT', page: 1, limit: 50 }, deps)).totalRecords, 2); assert.equal((await exploreStudents({ graduationYear: 2027, minCpi: 8, maxCpi: 9, backlog: 'zero', collegeEligibility: 'eligible', placementStatus: 'placed', verificationStatus: 'verified', company: 'c1', drive: 'd1', outcomeType: 'full_time', phase: 3, applicationStatus: 'placement_confirmed', page: 1, limit: 50 }, deps)).totalRecords, 1); assert.equal((await exploreStudents({ placementStatus: 'placed', outcomeType: 'internship', page: 1, limit: 50 }, deps)).totalRecords, 1) })
test('Explorer sorting is deterministic and pagination returns requested page metadata', async () => { const cpi = await exploreStudents({ sortBy: 'cgpa', sortOrder: 'desc', page: 1, limit: 25 }, deps); assert.deepEqual(cpi.records.map(item => item.id), ['s1', 's2', 's3']); const paged = await exploreStudents({ sortBy: 'name', sortOrder: 'asc', page: 2, limit: 2 }, deps); assert.deepEqual([paged.totalRecords, paged.totalPages, paged.records.map(item => item.id)], [3, 2, ['s3']]) })
test('Explorer branch grouping reports total, placed, unplaced eligible, and ineligible counts without private fields', async () => { const result = await exploreStudents({ groupBy: 'branch', page: 1, limit: 100 }, deps); assert.deepEqual(result.groupSummary, [{ branch: 'CSE', count: 1, placed: 1, unplacedEligible: 0, ineligible: 1 }, { branch: 'IT', count: 2, placed: 1, unplacedEligible: 0, ineligible: 1 }]); assert.equal('storagePath' in result.records[0], false); assert.equal('notes' in result.records[0], false) })
