import { Link, NavLink } from 'react-router-dom'
import { features, pageContent, photos, sampleStats } from './public-content.js'
import '../../styles/public-marketing.css'

const links = [['/', 'Home'], ['/institutions', 'Institutions'], ['/employers', 'Employers'], ['/students', 'Students']]
const companies = ['Nexora', 'Vertex', 'cloudlane', 'Helix', 'stride', 'infinova']
const iconPaths = {
  building: 'M3 21h18M5 21V7l7-4 7 4v14M9 9v2m6-2v2m-6 3v2m6-2v2m-4 5v-3h2v3',
  people: 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m20 0v-2a4 4 0 0 0-3-3.87M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8m8-7a4 4 0 0 1 0 8',
  file: 'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8ZM14 2v6h6M8 13h8m-8 4h6',
  profile: 'M4 3h16v18H4ZM12 7a3 3 0 1 0 0 6 3 3 0 0 0 0-6M7 18c0-4 10-4 10 0',
  chart: 'M4 21V11h3v10m4 0V3h3v18m4 0V7h3v14',
  shield: 'm12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6ZM8 12l3 3 5-6',
  spark: 'm12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3ZM20 2v4m-2-2h4',
  settings: 'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',
  calendar: 'M4 5h16v16H4ZM4 10h16M8 2v6m8-6v6M8 14h2m4 0h2m-8 3h2',
  bolt: 'm13 2-9 12h7l-1 8 10-13h-8Z',
  target: 'M21 12a9 9 0 1 1-9-9m5 9a5 5 0 1 1-5-5m0 5L22 2m-5 0h5v5',
  star: 'm12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z',
}
function Icon({ name = 'spark', tone = 0 }) { return <span className={`mk-icon mk-tone-${tone % 6}`}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={iconPaths[name] || iconPaths.spark} /></svg></span> }
function Brand() { return <Link to="/" className="mk-brand" aria-label="PlacementHub by AIT home"><span className="mk-ait-mark">A</span><span className="mk-ait"><b>AIT</b><small>Apex Institute of Technology</small></span><span className="mk-wordmark"><b>Placement<span>Hub</span></b><small>Connect　Prepare　Place　Together</small></span></Link> }
function Header() { return <header className="mk-header"><div className="mk-wrap"><Brand /><nav aria-label="Public pages">{links.map(([to, label]) => <NavLink key={to} to={to} end>{label}</NavLink>)}<Link to="/help-support" className="mk-help">Help &amp; Support</Link></nav><div className="mk-header-actions"><Link to="/login">Log in</Link><Button to="/register">Get started</Button></div></div></header> }
function Button({ to, href, light = false, children }) { const cls = `mk-button ${light ? 'mk-button-light' : ''}`; return href ? <a className={cls} href={href}>{children}<span aria-hidden="true">→</span></a> : <Link className={cls} to={to || '/register'}>{children}<span aria-hidden="true">→</span></Link> }
function Heading({ eyebrow, title, text, children }) { return <div className="mk-heading"><div><p className="mk-eyebrow">{eyebrow}</p><h2>{title}</h2>{text && <p>{text}</p>}</div>{children}</div> }
function Logos({ compact = false }) { return <div className={`mk-logos ${compact ? 'mk-logos-compact' : ''}`}>{companies.map((name, i) => <span className={`mk-logo mk-company-${i}`} key={name}><i aria-hidden="true">{['◈', '▦', '⌁', '✳', '↗', '∞'][i]}</i>{name}</span>)}</div> }
function Bars({ mini = false }) { return <div className={`mk-bars ${mini ? 'mk-bars-mini' : ''}`} aria-label="Illustrative placement rates: 78, 84, 91, 94, and 96 percent"><div>{[78, 84, 91, 94, 96].map((n, i) => <div key={n}><b>{n}%</b><i style={{ height: `${36 + i * 13}%` }} /><small>{2022 + i}</small></div>)}</div></div> }
function Dashboard({ audience }) {
  const employer = audience === 'employers', student = audience === 'students'
  const metrics = employer ? [['428', 'Applications'], ['120', 'Shortlisted'], ['48', 'Interviews'], ['18', 'Offers']] : student ? [['12', 'Applications'], ['4', 'Interviews'], ['2', 'Offers'], ['96', 'Profile views']] : [['1,248', 'Verified students'], ['186', 'Employers'], ['42', 'Active drives'], ['96%', 'Placement rate']]
  return <div className="mk-dashboard" aria-label={`${audience} dashboard design preview with sample data`}><div className="mk-dash-top"><b><span>◈</span> Placement<span>Hub</span></b><span className="mk-search">⌕　Search drives, students, opportunities…</span><span>♧　◉　<span className="mk-dot-avatar">A</span></span></div><div className="mk-dash-body"><aside>{['Overview', ...(student ? ['Find drives', 'My applications', 'My profile', 'Notifications', 'AI preparation'] : employer ? ['Create proposal', 'Applicants', 'Recruitment', 'Notifications', 'Analytics'] : ['Students', 'Employers', 'Placement drives', 'Monitoring', 'Reports'])].map((x, i) => <span key={x} className={i === 0 ? 'selected' : ''}><span>{['▦', '▣', '♧', '▤', '◷', '▥'][i]}</span>{x}</span>)}</aside><div className="mk-dash-main"><h3>{employer ? 'Welcome back, Nexora' : student ? 'Welcome back, Arjun!' : 'AIT · Training & Placement Cell'}</h3><p>Your next opportunity starts with a clear view.</p><div className="mk-dash-metrics">{metrics.map(([n, label], i) => <div key={label}><Icon name={['people', 'building', 'file', 'shield'][i]} tone={i} /><span><b>{n}</b><small>{label}</small></span></div>)}</div><div className="mk-dash-panels"><div><b>{employer ? 'Application trends' : 'Placement overview'}</b><Bars mini /></div><div><b>{student ? 'Opportunities for you' : 'Campus recruiter network'}</b><Logos compact /></div></div><small className="mk-demo">Product preview · sample data · includes planned features</small></div></div></div>
}
function Hero({ audience }) {
  const content = pageContent[audience]
  return <section className={`mk-hero mk-hero-${audience}`}><img className="mk-hero-photo" src={photos[audience]} alt={audience === 'employers' ? 'Recruiter team collaborating on campus hiring' : audience === 'institutions' ? 'AIT placement coordinators reviewing student opportunities' : 'Students at the Apex Institute campus'} fetchPriority="high" /><div className="mk-hero-wash" /><div className="mk-wrap mk-hero-inner"><div className="mk-hero-copy"><p className="mk-eyebrow">{content.eyebrow}</p><h1>{content.title[0]}<br /><em>{content.title[1]}</em><br />{content.title[2]}</h1><p>{content.description}</p><div className="mk-actions"><Button to={audience === 'institutions' ? '/help-support' : '/register'}>{content.action}</Button><Button href={`#${content.anchor}`} light>{content.secondary}</Button></div></div><span className="mk-handwritten">{content.note}</span><div className="mk-hero-stats">{sampleStats.map(([value, label, caption], i) => <article key={label}><Icon name={['shield', 'chart', 'people', 'building'][i]} tone={i} /><strong>{value}</strong><b>{label}</b><small>{caption}</small></article>)}</div><Dashboard audience={audience} /></div></section>
}
function FeatureGrid({ audience, title, eyebrow, text }) { return <section className="mk-section mk-wrap" id="ecosystem"><Heading eyebrow={eyebrow} title={title} text={text} /><div className="mk-feature-grid">{features[audience].map(([icon, name, description, planned], i) => <article className="mk-card" key={name}><Icon name={icon} tone={i} /><h3>{name}</h3><p>{description}</p>{planned && <small className="mk-planned">{planned}</small>}</article>)}</div></section> }
function PhotoTiles({ student = false }) {
  const tiles = student ? [['Explore Opportunities', 'Find eligible campus drives and roles that match your next step.', 'students', '#opportunities', 'building'], ['Prepare Smarter', 'Discover the roadmap for AI resume and interview guidance.', 'employers', '#ecosystem', 'spark'], ['Build Your Profile', 'Bring your academics, resume, projects, and skills together.', 'institutions', '/register', 'profile'], ['Get Placed', 'Discover the path from an application to your first job.', 'success', '#journey', 'star']] : [['For Institutions', 'Streamline placement operations with connected tools and insights.', 'campus', '/institutions', 'building'], ['For Employers', 'Discover verified talent and build your next great team.', 'employers', '/employers', 'file'], ['For Students', 'Prepare, apply, and grow your career with confidence.', 'students', '/students', 'profile'], ['About AIT', 'One campus. A community of future-ready professionals.', 'campus', '/institutions', 'shield']]
  return <section className="mk-wrap mk-photo-tiles">{tiles.map(([title, text, image, to, icon], i) => { const body = <><img src={photos[image]} alt="" loading="lazy" /><div><Icon name={icon} tone={i} /><span><h3>{title}</h3><p>{text}</p></span><span className="mk-round-arrow" aria-hidden="true">→</span></div></>; return to.startsWith('#') ? <a href={to} key={title}>{body}</a> : <Link to={to} key={title}>{body}</Link> })}</section>
}
function OutcomeBand() { return <section className="mk-wrap mk-outcome-band"><div className="mk-dark-copy"><p className="mk-eyebrow">Opportunity. Progress. Possibility.</p><h2>Our Placement Vision<br />Speaks Volumes</h2><p>From first applications to career-defining offers, every student journey deserves to be seen.</p><Button href="#placement-record" light>Explore placement outcomes</Button><small>Illustrative results, not audited AIT statistics.</small></div><article className="mk-card"><h3><Icon name="chart" tone={1} />96%</h3><p>Sample placement rate</p><Bars /></article><article className="mk-card"><h3><Icon name="star" tone={5} />₹ 54 LPA</h3><p>Sample highest package</p><div className="mk-package-list">{[['₹ 54 LPA', 'International role'], ['₹ 32 LPA', 'Product engineering'], ['₹ 28 LPA', 'Data & analytics'], ['₹ 18 LPA', 'Software engineering'], ['₹ 12 LPA', 'Graduate role']].map(([value, label]) => <div key={value}><b>{value}</b><span>{label}</span></div>)}</div></article><article className="mk-card"><h3><Icon name="people" tone={2} />1,200+</h3><p>Sample offers received</p><svg className="mk-line-chart" viewBox="0 0 180 125" role="img" aria-label="Illustrative growth in offers"><path d="M10 100 50 80 90 59 130 36 170 12" fill="none" stroke="#0861ed" strokeWidth="3" />{[[10,100],[50,80],[90,59],[130,36],[170,12]].map(([x,y],i)=><g key={x}><circle cx={x} cy={y} r="4" fill="#0861ed" /><text x={x} y={y-9} textAnchor="middle">{[320,540,780,980,1200][i]}</text></g>)}</svg></article><article className="mk-card"><h3><Icon name="building" />150+</h3><p>Sample recruiter network</p><Logos compact /><small className="mk-demo">Original fictional company brands</small></article></section> }
function Workflow({ institution = false }) { const steps = institution ? [['Onboard Students', 'Verify profiles, academics, and policy acceptance.'], ['Engage Employers', 'Approve companies and review their proposals.'], ['Conduct Drives', 'Publish roles, set eligibility, and monitor applicants.'], ['Track & Analyse', 'Recruitment phases in M7; reporting and exports in M8.'], ['Showcase Success', 'Connect placement outcomes to the student journey.']] : [['College Onboarding', 'The placement cell sets up profiles, policies, and approvals.'], ['Company Drives', 'Employers propose roles, eligibility, and recruitment plans.'], ['Student Applications', 'Verified students check eligibility and apply.'], ['Shortlists & Offers', 'Company-defined phase execution is planned in M7.'], ['First Job, Brighter Future', 'Turn preparation and opportunity into a confident first step.']]; return <section className={`mk-wrap mk-section mk-workflow ${institution ? 'mk-workflow-panel' : ''}`} id="workflow"><div>{institution ? <><p className="mk-eyebrow">Streamlined workflow</p><h2>A Simple, Structured Placement Process</h2><p>From onboarding students to closing offers, keep the whole journey connected.</p><Button href="#institution-tools" light>Explore the process</Button></> : <Heading eyebrow="From campus to career" title="A Simple, Powerful Placement Workflow" text="You focus on your goals. We help connect the next steps." />}</div><div className="mk-steps">{steps.map(([name, text], i) => <article key={name}><Icon name={['building', 'calendar', 'file', 'people', 'star'][i]} tone={i} /><h3>{i + 1}. {name}</h3><p>{text}</p></article>)}</div></section> }
function FutureBand() { return <section className="mk-future" id="future"><div className="mk-wrap"><div><p className="mk-eyebrow">AI + community = a stronger you</p><h2>Smart Tools. Real People.<br />Brighter Careers.</h2><p>A growing space for personalized preparation, shared learning, and inspiring first-job journeys.</p><Button to="/students">Explore the student journey</Button></div><article className="mk-card mk-resume"><h3><Icon name="file" />AI Resume Feedback</h3><small className="mk-planned">Planned · M10</small><p>Your advisory resume score</p><strong>85<small>/100</small></strong><progress value="85" max="100" aria-label="Example resume score" />{['Content & structure', 'Skills & projects', 'Impact & achievements', 'Clarity & formatting'].map(x => <p key={x}><span>✓</span>{x}<span>✓</span></p>)}</article><article className="mk-card"><h3><Icon name="profile" tone={1} />Interview Preparation</h3><img className="mk-card-photo" src={photos.institutions} alt="Student preparing with a placement coordinator" loading="lazy" /><p>Practice topics. Better answers. More confidence.</p><small className="mk-planned">Advisory AI · Planned M10</small></article><article className="mk-card"><h3><Icon name="people" tone={2} />Student Community</h3><div className="mk-person"><Avatar index={0} /><span><b>AITians</b><small>A shared campus journey</small></span></div><p>“One project, a few helpful conversations, and a little more confidence for my next interview.”</p><div className="mk-reactions">♡ 432　♧ 56</div><small className="mk-planned">Posts & comments · M9</small></article><article className="mk-story-photo"><img src={photos.success} alt="Graduate celebrating a career milestone" loading="lazy" /><div><b>Every first job has a story.</b><p>Make yours a story of preparation, persistence, and possibility.</p><small>Illustrative student journey</small></div></article></div></section> }
function Avatar({ index = 0 }) { return <span className={`mk-avatar mk-avatar-${index}`}><img src={index === 1 ? photos.employers : photos.home} alt="" loading="lazy" /></span> }
function Testimonials({ audience = 'home' }) { const roles = audience === 'employers' ? ['Campus recruiter', 'Talent acquisition', 'Hiring manager'] : audience === 'institutions' ? ['Placement coordinator', 'Faculty mentor', 'Campus recruiter'] : ['Student perspective', 'Placement cell perspective', 'Employer perspective']; const quotes = audience === 'students' ? ['A verified profile, a relevant drive, and clear updates — a stronger foundation for a first job.', 'Preparation feels more manageable when the next step is clear.', 'The journey matters as much as the offer. Learn, apply, and keep growing.'] : ['One connected placement journey makes it easier to understand what comes next.', 'Verified information and clear communication help everyone work with confidence.', 'A focused applicant pool brings more context to every hiring conversation.']; return <section className="mk-wrap mk-section" id="placement-record"><Heading eyebrow="Voices from the placement journey" title={audience === 'students' ? 'Placed Students, Real Possibilities' : audience === 'employers' ? 'A Better Experience for Every Recruiter' : 'Built for Students, Institutions & Employers'} text="Illustrative perspectives — not verified testimonials." /><div className="mk-testimonials">{quotes.map((quote, i) => <article className="mk-card" key={quote}><Avatar index={i} /><div><span className="mk-quote">“</span><p>{quote}</p><b>{roles[i]}</b><small>Apex Institute of Technology</small>{audience === 'students' && <span className="mk-pill">{['Software engineering', 'Data & analytics', 'Product development'][i]}</span>}</div></article>)}</div></section> }
function InstitutionIntro() { return <section className="mk-wrap mk-institution-intro"><img src={photos.campus} alt="AIT campus buildings" loading="lazy" /><div><h2>Partner with AIT for<br />Institutional Excellence</h2><p>Bring students, employers, and placement decisions together to build a better campus experience.</p></div>{[['shield', 'Greater Placement Readiness', 'Help more students enter the placement season with confidence.'], ['building', 'Stronger Industry Connections', 'Build lasting relationships with approved employers.'], ['chart', 'Outcome-Driven Decisions', 'A foundation for placement reports and analytics in M8.'], ['file', 'Efficient Placement Operations', 'Keep reviews, policies, and communication connected.']].map(([icon,title,text],i)=><article key={title}><Icon name={icon} tone={i}/><h3>{title}</h3><p>{text}</p></article>)}</section> }
function InstitutionDetails() { return <section className="mk-wrap mk-institution-details" id="institution-tools"><article className="mk-detail"><div><p className="mk-eyebrow">Engage trusted employers</p><h2>Build Lasting Industry Partnerships</h2><p>Review company onboarding, approve proposals, and connect students to well-defined opportunities.</p><Button to="/employers">Explore the employer experience</Button></div><div className="mk-detail-visual"><img src={photos.employers} alt="Hiring team planning campus recruitment" loading="lazy" /><div className="mk-floating"><b>Connected employer network</b><Logos compact /></div></div></article><article className="mk-detail"><div><p className="mk-eyebrow">Data-driven decisions · planned M8</p><h2>Comprehensive Analytics & Reporting</h2><p>Placement trends, outcomes, and Excel exports will help turn the season’s activity into useful insight.</p><Button href="#placement-record">Explore placement outcomes</Button></div><div className="mk-card mk-report"><b>Placement overview</b><div className="mk-report-stats"><strong>96%<small>Sample rate</small></strong><strong>1,248<small>Profiles</small></strong><strong>150+<small>Companies</small></strong></div><Bars mini /><small className="mk-demo">Illustrative report</small></div></article><article className="mk-detail"><div><p className="mk-eyebrow">Student readiness & verification</p><h2>Confident, Placement-Ready Graduates</h2><p>Verify academic records and resumes. Keep eligibility, policy acceptance, incidents, and restrictions in context.</p><Button to="/students">Explore student readiness</Button></div><div className="mk-detail-visual"><img src={photos.students} alt="AIT students ready for the next step" loading="lazy" /><div className="mk-floating mk-checklist">{['Verified student profiles', 'Academics, skills & resumes', 'Eligibility & policies', 'Drive monitoring'].map(x => <p key={x}><span>✓</span>{x}</p>)}</div></div></article><article className="mk-detail"><div><p className="mk-eyebrow">Connected communication</p><h2>Keep Everyone Moving Together</h2><p>Send relevant notifications, follow application activity, and help students and employers understand their next steps.</p><Button to="/help-support">Get help & support</Button></div><div className="mk-detail-visual"><img src={photos.institutions} alt="Placement team supporting students" loading="lazy" /><div className="mk-floating mk-checklist"><p>✓　Drive updates</p><p>✓　Applicant communication</p><p>✓　Policy context</p><p>✓　Help & guidance</p></div></div></article></section> }
function HiringBand() { return <section className="mk-wrap mk-hiring-band" id="hiring"><div className="mk-dark-copy"><p className="mk-eyebrow">Talent + technology + trust</p><h2>A Smarter Way to<br />Hire Campus Talent</h2><p>From creating proposals to meeting your applicant pool, bring the hiring journey into focus.</p><Button href="#hiring-features" light>Explore hiring features</Button></div><article className="mk-card"><h3><Icon name="file" tone={1} />Create a Campus Drive</h3><p>Define the role, eligibility, documents, and company recruitment plan.</p><ol className="mk-check-steps">{['Company onboarding & approval', 'Role details & documents', 'Eligibility & recruitment plan', 'Proposal review & publication'].map(x => <li key={x}><span>✓</span>{x}</li>)}</ol></article><article className="mk-card"><h3><Icon name="profile" tone={5} />Manage Applications</h3><p>Review applicant profiles with academic and skill context.</p>{['Riya Sharma', 'Aditya Verma', 'Sneha Patel'].map((name,i)=><div className="mk-candidate" key={name}><Avatar index={i}/><div><b>{name}</b><small>{['Computer Science · 8.8 CGPA','Information Technology · 8.4 CGPA','Electronics · 8.6 CGPA'][i]}</small></div><span>Applied</span></div>)}<small className="mk-demo">Illustrative applicant profiles</small></article><article className="mk-card"><h3><Icon name="chart" />Track Hiring Progress</h3><p>Phase execution in M7. Analytics and exports in M8.</p>{[['1,240','Applications',92],['420','Shortlisted',64],['128','Interviews',39],['42','Offers',20]].map(([n,label,width])=><div className="mk-pipeline" key={label}><span><b>{n}</b><small>{label}</small></span><i><span style={{width:`${width}%`}}/></i></div>)}<small className="mk-demo">Illustrative recruitment pipeline</small></article></section> }
function HiringFeatures() { return <section className="mk-wrap mk-section" id="hiring-features"><Heading eyebrow="End-to-end campus hiring" title="Everything You Need to Hire, in One Place" /><div className="mk-inline-features">{[['calendar','Create Hiring Drives','Roles, eligibility, and proposal review.'],['profile','Access Applicant Profiles','Verified academics, skills, and resumes.'],['people','Recruitment Phases','Candidate progression · planned M7.'],['file','Communicate Clearly','Drive updates for active applicants.'],['shield','Record Selections','Offer outcomes · planned M7.'],['chart','Track & Analyse','Reports and exports · planned M8.']].map(([icon,title,text],i)=><article key={title}><Icon name={icon} tone={i}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section> }
function TalentBand() { return <section className="mk-wrap mk-talent"><article className="mk-story-photo"><img src={photos.students} alt="AIT students on campus" loading="lazy"/><div><h2>Skilled Minds.<br/>Real Opportunities.</h2><p>Connect with motivated, future-ready students across disciplines.</p></div></article><article className="mk-card"><p className="mk-eyebrow">Talent at a glance</p><h2>Diverse, Skilled, and Ready<br/>to Make an Impact</h2><p>Explore academic backgrounds and practical skills in each applicant profile.</p><div className="mk-disciplines">{[['60%','Computer Science & IT'],['18%','Electronics'],['12%','Mechanical'],['8%','Civil'],['2%','Other disciplines']].map(([n,label])=><div key={label}><b>{n}</b><small>{label}</small></div>)}</div><small className="mk-demo">Illustrative discipline mix</small></article><article className="mk-card"><h3>Featured Candidate <span className="mk-demo">Sample profile</span></h3><div className="mk-person"><Avatar/><div><h2>Ananya Rao</h2><span className="mk-verified">✓ Verified profile</span><p>Computer Science<br/>CGPA: 8.7 · 2026 Batch</p></div></div><div className="mk-tags">{['Python','Web development','Problem solving','Communication'].map(x=><span key={x}>{x}</span>)}</div></article></section> }
function Recruiters() { return <section className="mk-wrap mk-section"><Heading eyebrow="Possibilities across industries" title="A Campus Network Built for Opportunity" text="Technology, engineering, analytics, and more. Original company identities shown for illustration."/><Logos/></section> }
function StudentOpportunities() { return <section className="mk-wrap mk-student-grid" id="opportunities"><div><Heading eyebrow="Featured opportunities · illustrative roles" title="Your Next Opportunity Starts Here" text="Discover the kinds of roles you can explore through published campus drives."/><div className="mk-jobs">{[['Software Engineer','Nexora','Bengaluru','₹ 12–18 LPA'],['Graduate Developer','Vertex','Hyderabad','₹ 8–12 LPA'],['Data Analyst','cloudlane','Bengaluru','₹ 8–14 LPA'],['Associate Engineer','Helix','Pune','₹ 8–10 LPA']].map(([role,company,location,salary])=><article className="mk-card" key={role}><h3>{role}</h3><b className="mk-job-company">{company}</b><p>{location}</p><div className="mk-tags"><span>Full time</span><span>{salary}</span></div><Link to="/login">Sign in to explore drives →</Link></article>)}</div></div><article className="mk-journey" id="journey"><img src={photos.success} alt="Graduate looking toward a first career opportunity" loading="lazy"/><div><p className="mk-eyebrow">From campus to career</p><h2>Your First Job.<br/>A Few Steps Away.</h2><p>Build your profile. Find your fit.<br/>Take the next step with confidence.</p><Button to="/register" light>Start your journey</Button></div><ol>{['Learn','Prepare','Apply','Interview','Get placed'].map(x=><li key={x}>{x}</li>)}</ol></article><Testimonials audience="students"/><article className="mk-card mk-student-record"><div><p className="mk-eyebrow">Our placement vision</p><h2>Consistent Progress.<br/>Brighter Futures.</h2><p>Every student deserves a clear path from preparation to opportunity.</p><small>Illustrative placement results</small></div><Bars/></article></section> }
function Community() { return <section className="mk-wrap mk-community"><div><p className="mk-eyebrow">A supportive community · planned M9</p><h2>Learn Together. Grow Together.</h2><p>A campus space for posts, likes, and conversations.</p><Button href="#future-community">Explore community plans</Button></div><div id="future-community">{[['people','Campus Conversations','Ask, share, and learn from each other.'],['profile','Student Stories','Share the experience behind your journey.'],['file','Placement Updates','Discuss opportunities and preparation.'],['shield','Peer Support','Build confidence through shared learning.']].map(([icon,title,text],i)=><article className="mk-card" key={title}><Icon name={icon} tone={i}/><span><h3>{title}</h3><p>{text}</p><small className="mk-planned">Planned community feature</small></span></article>)}</div></section> }
function Closing({ audience }) { return <section className="mk-closing"><img src={photos.campus} alt="AIT campus at sunset" loading="lazy"/><div className="mk-wrap"><p className="mk-eyebrow">Let’s build brighter tomorrows together</p><h2>{pageContent[audience].closing}</h2><p>For students, the placement cell, and employers — a shared path from potential to possibility.</p><div className="mk-actions"><Button to={audience === 'institutions' ? '/help-support' : '/register'}>{audience === 'employers' ? 'Start hiring' : audience === 'institutions' ? 'Connect with our team' : 'Get started now'}</Button><Button to="/help-support" light>Talk to our team</Button></div></div></section> }
function Footer() { return <footer className="mk-footer"><div className="mk-wrap"><Brand/><div><nav aria-label="Footer navigation">{links.map(([to,label])=><Link to={to} key={to}>{label}</Link>)}<Link to="/help-support">Help &amp; Support</Link></nav><small>© {new Date().getFullYear()} Apex Institute of Technology · Building careers. Shaping futures.</small></div><span>Connect. Prepare.<br/><b>Place. Together.</b></span></div><p className="mk-disclosure">Public product showcase: statistics, companies, candidate profiles, and stories are illustrative. Recruitment execution (M7), analytics/exports (M8), community (M9), and advisory AI (M10) are planned; final QA and deployment follow in M11.</p></footer> }
export function PublicPage({ audience }) { return <div className={`marketing-site mk-page-${audience}`}><Header/><Hero audience={audience}/>{audience === 'home' && <><PhotoTiles/><FeatureGrid audience="home" eyebrow="Why PlacementHub" title="A Complete Placement Ecosystem" text="Powerful tools for a seamless, transparent, and successful placement journey."/><OutcomeBand/><Workflow/><FutureBand/><Testimonials/></>}{audience === 'institutions' && <><InstitutionIntro/><FeatureGrid audience={audience} eyebrow="Powerful tools for your placement cell" title="Everything Your Placement Cell Needs, in One Platform"/><Workflow institution/><InstitutionDetails/><Testimonials audience={audience}/></>}{audience === 'employers' && <><FeatureGrid audience={audience} eyebrow="Why recruit at AIT" title="Access Job-Ready Talent. Create Real Impact." text="Partner with us to connect with skilled, motivated students through a focused campus hiring experience."/><HiringBand/><HiringFeatures/><TalentBand/><Recruiters/><Testimonials audience={audience}/></>}{audience === 'students' && <><PhotoTiles student/><FeatureGrid audience={audience} eyebrow="Smart tools for a brighter career" title={<>Everything You Need to<br/>Ace Your Placement Journey</>} text="From preparation to applications, support for every step."/><StudentOpportunities/><Community/></>}<Closing audience={audience}/><Footer/></div> }
