import { Link } from 'react-router-dom'
import { ProfileAvatar } from './ProfileAvatar.jsx'
export function ProfileHeader({ profile, token, social = false }) {
  return <header className="rounded-2xl border border-blue-100 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start gap-4"><ProfileAvatar role={profile.role} name={profile.name} userId={profile.userId} hasAvatar={profile.hasAvatar} avatarVersion={profile.avatarVersion} token={token} circular={social} /><div className="min-w-0"><span className="text-xs font-bold uppercase tracking-wide text-blue-800">{profile.label}</span><h1 className="mt-1 break-words text-2xl font-extrabold text-slate-950">{profile.name}</h1><p className="mt-2 break-words text-sm text-blue-900">{profile.headline || profile.industry}</p><p className="mt-1 text-sm text-slate-500">{[profile.branch, profile.graduationYear, profile.role === 'company' && profile.headline ? profile.industry : null, profile.location].filter(Boolean).join(' · ')}</p>{profile.institutionName && <p className="mt-2 text-sm font-semibold">{profile.institutionName}</p>}</div></div></header>
}
const safe = url => { try { const parsed = new URL(url); return ['http:', 'https:'].includes(parsed.protocol) && !parsed.username && !parsed.password } catch { return false } }
function External({ url, children }) { return safe(url) ? <a className="break-all font-semibold text-blue-800 hover:underline" href={url} target="_blank" rel="noreferrer">{children}</a> : null }
export function SocialProfileView({ profile, viewerRole, token }) {
  const groups = [['interests','Interests'],['softSkills','Soft skills'],['hobbies','Hobbies'],['achievementHighlights','Achievement highlights'],['clubs','Clubs / societies'],['extracurriculars','Extracurricular activities'],['volunteering','Volunteering'],['currentlyLearning','Currently learning'],['lookingToExplore','Looking to explore'],['languages','Languages'],['hiringDomains','Hiring domains']]
  return <div className="space-y-4"><ProfileHeader profile={profile} token={token} social />
    {profile.about && <Section title={profile.role === 'student' ? 'About Me' : 'About'}><p className="whitespace-pre-wrap break-words">{profile.about}</p></Section>}
    {groups.filter(([key]) => profile[key]?.length).map(([key,title]) => <Section key={key} title={title}><Chips values={profile[key]} /></Section>)}
    {profile.personalityType && <Section title="Personality"><p>{profile.personalityType} · Self-selected</p></Section>}
    {profile.skills?.length > 0 && <Section title="Skills preview"><Chips values={profile.skills} /></Section>}
    {profile.website && <Section title="Website"><External url={profile.website}>{profile.website}</External></Section>}
    {Object.keys(profile.links || {}).length > 0 && <Section title="Social / professional links"><div className="flex flex-wrap gap-4">{Object.entries(profile.links).map(([key,url]) => <External key={key} url={url}>{key}</External>)}</div></Section>}
    {(profile.representativeName || profile.designation || profile.publicEmail || profile.publicPhone || profile.representativeNote) && <Section title={profile.role === 'company' ? 'Account / recruiter representative' : 'Placement office contact'}><p className="font-semibold">{[profile.representativeName, profile.designation].filter(Boolean).join(' · ')}</p>{profile.publicEmail && <p className="break-all">{profile.publicEmail}</p>}{profile.publicPhone && <p>{profile.publicPhone}</p>}{profile.representativeNote && <p className="whitespace-pre-wrap break-words">{profile.representativeNote}</p>}</Section>}
    {profile.role === 'student' && profile.canViewMainProfile && ['company', 'placement_admin'].includes(viewerRole) && <Link className="inline-block rounded-xl bg-blue-900 px-4 py-2 text-sm font-bold text-white" to={`/community/profiles/${profile.userId}/main-profile`}>View Main Profile</Link>}
  </div>
}

function Section({ title, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="mb-3 text-lg font-bold text-slate-950">{title}</h2><div className="text-sm leading-7 text-slate-700">{children}</div></section> }
function Chips({ values }) { return <div className="flex flex-wrap gap-2">{[...new Set(values)].map(value => <span className="max-w-full break-words rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-900" key={value}>{value}</span>)}</div> }
const date = value => value ? new Date(value).toLocaleDateString([], { month: 'short', year: 'numeric' }) : ''
function Evidence({ title, items, kind }) {
  if (!items?.length) return null
  return <Section title={title}><div className="space-y-5">{items.map((item, i) => <article key={i} className={i ? 'border-t border-slate-100 pt-4' : ''}><h3 className="font-bold text-slate-900">{item.title || item.role}</h3><p className="text-xs text-slate-500">{[item.organization || item.issuer, item.title ? item.role : '', kind === 'experience' ? [date(item.startDate), item.endDate ? date(item.endDate) : 'Present'].filter(Boolean).join(' – ') : date(item.issuedOn || item.awardedOn)].filter(Boolean).join(' · ')}</p>{item.description && <p className="mt-2 whitespace-pre-wrap break-words">{item.description}</p>}{(item.technologies || item.skills)?.length > 0 && <div className="mt-2"><Chips values={item.technologies || item.skills} /></div>}{(item.url || item.credentialUrl) && <External url={item.url || item.credentialUrl}>View {kind === 'project' ? 'project' : 'credential / reference'}</External>}</article>)}</div></Section>
}
export function MainProfileView({ profile }) {
  const softSkills = profile.softSkills || []
  const technical = [...new Set((profile.skillGroups || []).flatMap(g => g.skills || []))].filter(skill => !softSkills.some(soft => soft.toLowerCase() === skill.toLowerCase()))
  const general = (profile.skills || []).filter(skill => ![...technical, ...softSkills].some(value => value.toLowerCase() === skill.toLowerCase()))
  return <div className="space-y-4"><ProfileHeader profile={profile} /><Section title="About"><p className="whitespace-pre-wrap break-words">{profile.about || 'A professional introduction has not been added yet.'}</p></Section>{(profile.targetRole || profile.careerInterests?.length > 0) && <Section title="Career interests">{profile.targetRole && <p className="mb-2 font-semibold">Target role: {profile.targetRole}</p>}<Chips values={profile.careerInterests || []} /></Section>}
    <Section title="Technical skills">{technical.length ? <Chips values={technical} /> : <p>No grouped technical skills added yet.</p>}{general.length > 0 && <div className="mt-4"><h3 className="mb-2 font-semibold">Other listed skills</h3><Chips values={general} /></div>}</Section><Section title="Soft skills">{softSkills.length ? <Chips values={softSkills} /> : <p>No separate soft skills added yet.</p>}</Section>
    <Evidence title="Projects" items={profile.projects} kind="project" /><Evidence title="Internships / experience" items={profile.internships} kind="experience" /><Evidence title="Certifications" items={profile.certifications} /><Evidence title="Achievements" items={profile.achievements} /><Evidence title="Extracurricular activities / clubs / volunteering" items={profile.extracurriculars} /><Evidence title="Leadership / responsibility" items={profile.leadership} />
    {(Object.keys(profile.professionalLinks || {}).length > 0 || profile.codingProfiles?.length > 0) && <Section title="Professional & coding links"><div className="flex flex-wrap gap-4">{Object.entries(profile.professionalLinks || {}).map(([label, url]) => <External key={label} url={url}>{label}</External>)}{(profile.codingProfiles || []).map((link, i) => <External key={i} url={link.url}>{link.platform}</External>)}</div></Section>}
  </div>
}
