import { useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { EmptyState } from '../components/feedback/EmptyState.jsx'
import { ErrorState } from '../components/feedback/ErrorState.jsx'
import { LoadingState } from '../components/feedback/LoadingState.jsx'
import { PageHeader } from '../components/ui/PageHeader.jsx'
import { useAuth } from '../features/auth/useAuth.js'
import { useCompanyExplorerAi } from '../features/ai/useCompanyExplorerAi.js'
import { CompanyExplorerTools } from '../features/ai/CompanyIntelligence.jsx'
import { exportCompanyCandidates, getCompanyCandidates } from '../services/company-analytics.service.js'

const selectOptions = [['status', 'Status', [['', 'All statuses'], ['active', 'Active'], ['rejected', 'Rejected'], ['absent', 'Absent'], ['withdrawn', 'Withdrawn'], ['selected_pending_confirmation', 'Provisional selected'], ['placement_confirmed', 'Placement confirmed']]], ['confirmationStatus', 'Confirmation', [['', 'All confirmation states'], ['selected_report_not_submitted', 'Report not submitted'], ['pending_admin_verification', 'Confirmation pending'], ['confirmed', 'Confirmed'], ['rejected', 'Rejected'], ['revoked', 'Revoked']]], ['phase', 'Phase', [['', 'All phases'], ['0', 'Phase 0'], ['1', 'Phase 1'], ['2', 'Phase 2'], ['3', 'Phase 3'], ['4', 'Phase 4'], ['5', 'Phase 5']]], ['outcomeType', 'Outcome', [['', 'All outcomes'], ['full_time', 'Full time'], ['ppo', 'PPO'], ['internship', 'Internship'], ['internship_and_ppo', 'Internship + PPO']]], ['sortBy', 'Sort', [['name', 'Name'], ['cgpa', 'CPI'], ['branch', 'Branch'], ['phase', 'Phase'], ['status', 'Status'], ['activity', 'Recent activity']]], ['sortOrder', 'Order', [['asc', 'Ascending'], ['desc', 'Descending']]], ['groupBy', 'Group', [['', 'No grouping'], ['branch', 'Branch'], ['phase', 'Phase'], ['status', 'Status']]], ['limit', 'Rows', [['25', '25 rows'], ['50', '50 rows'], ['100', '100 rows']]]]
const pretty = value => String(value ?? '—').replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase())

export function CompanyCandidateExplorerPage() {
  const { session } = useAuth(); const [params, setParams] = useSearchParams(); const filters = useMemo(() => Object.fromEntries(params.entries()), [params]); const [data, setData] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { let live = true; getCompanyCandidates(session.accessToken, { limit: 50, ...filters }).then(result => { if (live) { setError(''); setData(result.data) } }).catch(err => live && setError(err.message)); return () => { live = false } }, [session.accessToken, params, filters])
  const set = values => setParams(current => { const next = new URLSearchParams(current); Object.entries(values).forEach(([key, value]) => value === '' || value == null ? next.delete(key) : next.set(key, String(value))); if (!Object.hasOwn(values, 'page')) next.set('page', '1'); return next })
  const rows = data?.records ?? []; const intelligence = useCompanyExplorerAi(session.accessToken, rows); const chips = Object.entries(filters).filter(([key]) => !['page', 'limit'].includes(key))
  if (error && !data) return <ErrorState message={error} />
  if (!data) return <LoadingState message="Loading candidate explorer…" />
  const exportView = async exportMode => { try { setBusy(true); await exportCompanyCandidates(session.accessToken, { ...filters, page: data.page, limit: data.limit, exportMode }) } catch (err) { setError(err.message) } finally { setBusy(false) } }
  return <section className="space-y-5"><PageHeader eyebrow="Company analytics" title="Candidate Explorer" description={`${data.totalRecords} candidates across your drives`} action={<div className="flex gap-2"><button disabled={busy} className="rounded-xl border px-4 py-2 text-sm font-bold text-blue-800" onClick={() => exportView('current_view')}>Export Current View</button><button disabled={busy} className="rounded-xl border px-4 py-2 text-sm font-bold text-blue-800" onClick={() => exportView('all_matching')}>{busy ? 'Exporting…' : 'Export All Matching'}</button></div>} />
    {error && <ErrorState message={error} />}<section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-4"><input className="rounded-lg border p-2" placeholder="Name, roll number, or email" value={filters.search ?? ''} onChange={event => set({ search: event.target.value })} /><input className="rounded-lg border p-2" placeholder="Drive ID" value={filters.drive ?? ''} onChange={event => set({ drive: event.target.value })} /><input className="rounded-lg border p-2" placeholder="Branch" value={filters.branch ?? ''} onChange={event => set({ branch: event.target.value })} /><input className="rounded-lg border p-2" type="number" placeholder="Minimum CPI" value={filters.minCpi ?? ''} onChange={event => set({ minCpi: event.target.value })} /><input className="rounded-lg border p-2" type="number" placeholder="Maximum CPI" value={filters.maxCpi ?? ''} onChange={event => set({ maxCpi: event.target.value })} />{selectOptions.map(([key, name, options]) => <label key={key} className="text-xs font-bold text-slate-600">{name}<select className="mt-1 w-full rounded-lg border p-2 text-sm" value={filters[key] ?? (key === 'sortBy' ? 'name' : key === 'sortOrder' ? 'asc' : key === 'limit' ? '50' : '')} onChange={event => set({ [key]: event.target.value })}>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}{key === 'sortBy' && intelligence.enabled && <option value='objective_match'>Objective Match</option>}</select></label>)}</div><div className="mt-3 flex flex-wrap gap-2">{chips.map(([key, value]) => <button key={key} onClick={() => set({ [key]: '' })} className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-800">{pretty(key)}: {value} ×</button>)}<button className="ml-auto text-sm font-bold text-blue-700" onClick={() => setParams({})}>Clear All</button></div></section>
    {intelligence.enabled && <CompanyExplorerTools intelligence={intelligence} token={session.accessToken} rows={rows} />}
    {data.groupSummary && <section className="grid gap-3 md:grid-cols-3">{data.groupSummary.map(group => <button key={group.label} className="rounded-xl border bg-white p-4 text-left" onClick={() => set(data.appliedFilters.groupBy === 'branch' ? { branch: group.label, groupBy: '' } : data.appliedFilters.groupBy === 'phase' ? { phase: group.label.replace('Phase ', ''), groupBy: '' } : { status: group.label, groupBy: '' })}><strong>{pretty(group.label)}</strong><span className="mt-1 block text-sm text-slate-600">{group.count} candidates · Open →</span></button>)}</section>}
    {rows.length ? <div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><thead><tr>{[...(intelligence.enabled ? ['AI select'] : []), 'Name', 'Roll', 'Branch', 'CPI', 'Drive', 'Phase', 'Status', 'Confirmation', 'Outcome', ...(intelligence.enabled ? ['Objective Match', 'AI Fit', 'AI Status'] : []), 'View'].map(head => <th key={head} className="border-b bg-slate-50 p-3 text-left">{head}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.id}>{intelligence.enabled && <td className='border-b p-3'><input type='checkbox' aria-label={'Select ' + row.name + ' for AI'} checked={intelligence.selected.some(item => item.id === row.id)} disabled={row.aiAvailable === false || !intelligence.selected.some(item => item.id === row.id) && (intelligence.selected.length >= intelligence.limits.batch || intelligence.selected.length > 0 && intelligence.selected[0].driveId !== row.driveId)} onChange={() => intelligence.toggle(row)} /></td>}{[row.name, row.rollNumber || '—', row.branch || '—', row.cgpa ?? '—', row.drive?.role || '—', `Phase ${row.currentPhase}`, pretty(row.applicationStatus), pretty(row.confirmationStatus), pretty(row.outcomeType)].map((value, index) => <td key={index} className="border-b p-3">{value}</td>)}{intelligence.enabled && <><td className='border-b p-3'>{row.objectiveMatch?.score == null ? row.objectiveMatch?.label ?? 'Unavailable' : row.objectiveMatch.score + '%'}</td><td className='border-b p-3'>{intelligence.records[row.id]?.assessment ? intelligence.records[row.id].assessment.score + '%' : '—'}</td><td className='border-b p-3'>{intelligence.records[row.id]?.assessment ? intelligence.records[row.id].assessment.stale ? 'Refresh needed' : 'Analyzed' : (intelligence.job?.items.find(item => item.studentId === row.studentId && intelligence.job.driveId === row.driveId)?.status ?? 'Not analyzed')}</td></>}<td className="border-b p-3"><Link className="font-bold text-blue-700" to={`/company/placement-drives/${row.driveId}/applicants/${row.studentId}`}> {intelligence.enabled && intelligence.records[row.id]?.assessment ? 'View AI result' : 'View'}</Link>{intelligence.enabled && <button type="button" aria-label={'Analyze ' + row.name + ' with AI'} disabled={row.aiAvailable === false || Boolean(intelligence.job && intelligence.job.status !== 'completed')} onClick={() => intelligence.start([row])} className="mt-2 block text-xs font-bold text-blue-800 disabled:opacity-50">Analyze with AI</button>}</td></tr>)}</tbody></table></div> : <EmptyState title="No candidates match these filters" description="Clear filters or broaden the query." />}
    <footer className="flex justify-between text-sm"><span>Showing {rows.length ? (data.page - 1) * data.limit + 1 : 0}–{Math.min(data.page * data.limit, data.totalRecords)} of {data.totalRecords}</span><span className="flex gap-3"><button disabled={data.page === 1} onClick={() => set({ page: data.page - 1 })}>Previous</button><button disabled={data.page >= data.totalPages} onClick={() => set({ page: data.page + 1 })}>Next</button></span></footer>
  </section>
}
