import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { EmptyState } from '../components/feedback/EmptyState.jsx'
import { ErrorState } from '../components/feedback/ErrorState.jsx'
import { LoadingState } from '../components/feedback/LoadingState.jsx'
import { PageHeader } from '../components/ui/PageHeader.jsx'
import { StatusBadge } from '../components/ui/StatusBadge.jsx'
import { useAuth } from '../features/auth/useAuth.js'
import { usePlacementCycle } from '../features/placement-cycle/usePlacementCycle.js'
import { getMyStudentIdentityContext, getMyStudentProfile } from '../services/student.service.js'
import { getMyStudentPolicy } from '../services/student-policy.service.js'
import { getAdminDashboardSummary, getCompanyDashboardSummary, getStudentDashboardSummary } from '../services/dashboard.service.js'
import { listMyPlacementDrives, listAdminPublishedDriveMonitoring } from '../services/placement-drive.service.js'
import { listCompanyDriveApplicants } from '../services/company-drive-applicant.service.js'
import { getCompanyAnalytics } from '../services/company-analytics.service.js'
import { displayInstitutionName } from '../utils/institution-branding.js'
import { AdminCommandCenter } from '../components/analytics/AdminCommandCenter.jsx'
import { StudentIntelligence } from '../features/ai/StudentIntelligence.jsx'

const dateLabel = value => value ? new Date(value).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' }) : 'Not set'
const titleCase = value => value ? value.replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase()) : 'Not set'
const linkStyle = 'inline-flex min-h-10 items-center justify-center rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700 transition hover:border-slate-400 hover:bg-slate-50'
const primaryLinkStyle = 'inline-flex min-h-11 items-center justify-center rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-800'

export function DashboardPage() {
  const { session } = useAuth()
  if (session.user.role === 'student') return <StudentDashboard token={session.accessToken} name={session.user.name} />
  if (session.user.role === 'company') return <CompanyDashboard token={session.accessToken} name={session.user.name} />
  return <AdminCommandCenter token={session.accessToken} name={session.user.name} />
}

function StudentDashboard({ token, name }) {
  const [data, setData] = useState(null); const [profile, setProfile] = useState(null); const [identity, setIdentity] = useState(null); const [policyRequired, setPolicyRequired] = useState(false); const [error, setError] = useState('')
  useEffect(() => { let active = true; Promise.all([getStudentDashboardSummary(token), getMyStudentProfile(token), getMyStudentPolicy(token)]).then(([summary, profileResponse, policy]) => { if (active) { setData(summary.data); setProfile(profileResponse.data); setPolicyRequired(profileResponse.data.verificationStatus === 'verified' && !policy.data.acceptance) } }).catch(error => { if (active) setError(error.message) }); getMyStudentIdentityContext(token).then(({ data: context }) => { if (active) setIdentity(context) }).catch(() => { if (active) setIdentity(null) }); return () => { active = false } }, [token])
  if (error && !data) return <ErrorState message={error} />
  if (!data) return <LoadingState message="Loading your dashboard…" />
  const studentName = identity?.studentName || name || 'Student'
  const institutionName = displayInstitutionName(identity?.institutionName)
  const academicContext = [profile?.branch, profile?.graduationYear].filter(Boolean).join(' • ')
  return <section className="space-y-7"><PageHeader eyebrow="Student Placement Portal" title={`Welcome, ${studentName}.`} description={<><span className="block font-medium text-slate-700">{institutionName}</span>{academicContext && <span className="mt-1 block text-sm text-slate-500">{academicContext}</span>}</>} action={<Link className={primaryLinkStyle} to="/student/placement">Open Placement Center</Link>} />{policyRequired && <Link to="/student/policy" className="block rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-amber-950 shadow-sm"><strong>Placement policy action required</strong><span className="mt-1 block text-sm">Accept the active Student Placement Policy before participating in placement activities.</span></Link>}<SummaryBar items={[["Open Drives", data.publishedDriveCount], ["Eligible Drives", data.eligibleDriveCount], ["Active Applications", data.activeApplicationCount], ["Unread Notifications", data.unreadNotificationCount]]} /><StudentIntelligence token={token} revision={profile?.updatedAt} /><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-bold text-slate-950">Placement activity</h2><p className="mt-1 text-sm text-slate-600">Browse current opportunities or check your Phase 0 applications.</p></div><div className="flex gap-2"><Link className={linkStyle} to="/student/placement?tab=applications">My applications</Link><Link className={linkStyle} to="/student/notifications">Notifications</Link></div></div></section>{error && <ErrorState message={error} />}</section>
}

function CompanyDashboard({ token, name }) {
  const { cycle } = usePlacementCycle()
  const [summary, setSummary] = useState(null); const [analytics, setAnalytics] = useState(null); const [drives, setDrives] = useState(null); const [counts, setCounts] = useState({}); const [error, setError] = useState('')
  useEffect(() => { let active = true; Promise.all([getCompanyDashboardSummary(token), getCompanyAnalytics(token), listMyPlacementDrives(token)]).then(async ([summaryResponse, analyticsResponse, drivesResponse]) => { const published = drivesResponse.data.filter(drive => drive.lifecycleStatus === 'published'); const details = await Promise.all(published.map(drive => listCompanyDriveApplicants(token, drive._id).then(response => [drive._id, response.data.summary]).catch(() => [drive._id, null]))); if (active) { setSummary(summaryResponse.data); setAnalytics(analyticsResponse.data); setDrives(drivesResponse.data); setCounts(Object.fromEntries(details)) } }).catch(error => { if (active) setError(error.message) }); return () => { active = false } }, [token])
  if (error && !summary) return <ErrorState message={error} />
  if (!summary || !analytics || !drives) return <LoadingState message="Loading your Company dashboard…" />
  return <section className="space-y-7"><PageHeader eyebrow="Campus Recruitment Portal" title={`Welcome back, ${name}.`} description={cycle.id === '2026' ? 'Review completed 2025–26 recruitment history.' : 'Manage active applicant pools and current 2027 recruitment activity.'} action={<Link className={primaryLinkStyle} to="/company/placement-drives/new">Create proposal</Link>} /><SummaryBar items={[["Total drives", analytics.kpis.totalDrives], ["Active candidates", analytics.kpis.activeCandidates], ["Offers received", analytics.kpis.offersReceived], ["Confirmation pending", analytics.kpis.confirmationPending], ["Confirmed offers", analytics.kpis.confirmedOffers], ["Unread notifications", summary.unreadNotificationCount]]} /><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-blue-700">Candidate analytics</p><h2 className="mt-1 text-xl font-bold">Pipeline at a glance</h2><p className="mt-2 text-sm text-slate-600">{analytics.kpis.totalApplications} applications · {analytics.kpis.confirmationPending} confirmation pending · {analytics.kpis.rejected} rejected</p></div><Link className={linkStyle} to="/company/candidates">Open Candidate Explorer</Link></div></section><section className="grid gap-4 lg:grid-cols-2">{analytics.drives.map(drive => <article key={drive.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-slate-950">{drive.role || 'Placement Drive'}</h2><p className="mt-1 text-sm text-slate-600">{drive.applicantCount} applicants · {drive.activeCandidates} active · {drive.confirmed} confirmed</p></div><Link className="text-sm font-bold text-blue-700" to={`/company/placement-drives/${drive.id}/applicants`}>View history →</Link></div><div className="mt-4 space-y-2">{drive.phaseAnalytics.map(phase => <Link key={phase.phaseNumber} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm hover:bg-blue-50" to={`/company/candidates?drive=${drive.id}&phase=${phase.phaseNumber}`}><span>{phase.title}</span><span className="font-semibold text-slate-600">{phase.current} current · {phase.advanced} advanced</span></Link>)}</div></article>)}</section><section className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-blue-700">Main workspace</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-950">My Drives</h2></div><Link className={linkStyle} to="/company/placement-drives">All proposals</Link></div><DriveList drives={drives} counts={counts} /></section>{error && <ErrorState message={error} />}</section>
}

function DriveList({ drives, counts }) {
  if (!drives.length) return <EmptyState title="No Placement Drive proposals" description="Create a proposal when you are ready to recruit for a role." action={<Link className="font-bold text-blue-700 hover:underline" to="/company/placement-drives/new">Create proposal</Link>} />
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="hidden grid-cols-[minmax(13rem,1.6fr)_minmax(12rem,1.2fr)_8rem_8rem_8rem] gap-4 border-b border-slate-100 bg-slate-50 px-5 py-3 text-xs font-bold uppercase tracking-[0.08em] text-slate-500 lg:grid"><span>Drive</span><span>Status</span><span>Deadline</span><span>Applicants</span><span>Action</span></div><div className="divide-y divide-slate-100">{drives.map(drive => { const published = drive.lifecycleStatus === 'published'; const completed = drive.lifecycleStatus === 'completed'; const summary = counts[drive._id]; const action = published ? ['Manage', `/company/placement-drives/${drive._id}/applicants`, true] : completed ? ['View history', `/company/placement-drives/${drive._id}/applicants`, true] : drive.proposalStatus === 'changes_requested' ? ['Fix & Resubmit', `/company/placement-drives/${drive._id}`, true] : drive.proposalStatus === 'draft' ? ['Edit', `/company/placement-drives/${drive._id}`, true] : ['View', `/company/placement-drives/${drive._id}`, false]; return <article key={drive._id} className="grid gap-3 px-5 py-5 lg:grid-cols-[minmax(13rem,1.6fr)_minmax(12rem,1.2fr)_8rem_8rem_8rem] lg:items-center"><div><h3 className="font-bold text-slate-950">{drive.role?.title || 'Placement Drive'}</h3><p className="mt-1 text-sm text-slate-600">{drive.role?.domain || 'Role details'}</p></div><div className="flex flex-wrap gap-2"><StatusBadge status={drive.proposalStatus}>{titleCase(drive.proposalStatus)}</StatusBadge><StatusBadge status={drive.lifecycleStatus}>{published ? 'Live to Students' : completed ? 'Historical completed drive' : drive.proposalStatus === 'approved' ? 'Approved — not visible to Students yet' : titleCase(drive.lifecycleStatus)}</StatusBadge></div><Value label="Deadline" value={dateLabel(drive.driveDetails?.applicationDeadline)} /><Value label="Applicants" value={published ? (summary?.applicantCount ?? '—') : '—'} /><Link className={action[2] ? primaryLinkStyle : linkStyle} to={action[1]}>{action[0]}</Link></article> })}</div></section>
}

export function AdminDashboard({ token, name }) {
  const [summary, setSummary] = useState(null); const [drives, setDrives] = useState(null); const [error, setError] = useState('')
  useEffect(() => { let active = true; Promise.all([getAdminDashboardSummary(token), listAdminPublishedDriveMonitoring(token)]).then(([summaryResponse, driveResponse]) => { if (active) { setSummary(summaryResponse.data); setDrives(driveResponse.data) } }).catch(error => { if (active) setError(error.message) }); return () => { active = false } }, [token])
  if (error && !summary) return <ErrorState message={error} />
  if (!summary || !drives) return <LoadingState message="Loading the placement dashboard…" />
  const attention = [["Student verifications", summary.pendingStudentVerificationCount, '/admin/students'], ["Company approvals", summary.pendingCompanyApprovalCount, '/admin/companies'], ["Drive proposal reviews", summary.pendingDriveReviewCount, '/admin/placement-drives?status=submitted'], ["Incident / discipline reviews", summary.pendingIncidentReviewCount, '/admin/placement-discipline'], ["Unread Company notifications", summary.unreadNotificationCount, '/admin/notifications']]
  return <section className="space-y-7"><PageHeader eyebrow="Career Development Centre" title={`Welcome back, ${name}.`} description="Placement operations that need attention and active drives in one view." /><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><p className="text-xs font-bold uppercase tracking-[0.14em] text-blue-700">Operations</p><h2 className="mt-1 text-xl font-bold text-slate-950">Needs Attention</h2></div><div className="divide-y divide-slate-100">{attention.map(([label, count, to]) => <Link key={label} to={to} className="flex items-center justify-between gap-4 px-5 py-4 transition hover:bg-slate-50"><span className="font-semibold text-slate-800">{label}</span><span className="inline-flex items-center gap-2"><StatusBadge status={count ? 'pending' : 'neutral'}>{count}</StatusBadge><span className="text-sm font-bold text-blue-700">Open →</span></span></Link>)}</div></section><section className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-blue-700">Live placement activity</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-950">Active Placement Drives</h2></div><Link className={linkStyle} to="/admin/placement-drives/monitoring">Active Placement Drives</Link></div>{!drives.length ? <EmptyState title="No active Placement Drives" description="Published drives will appear here for active Drive operations." /> : <AdminDriveList drives={drives} />}</section>{error && <ErrorState message={error} />}</section>
}

function AdminDriveList({ drives }) { return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="hidden grid-cols-[minmax(12rem,1.3fr)_minmax(12rem,1.3fr)_7rem_7rem_8rem] gap-4 border-b border-slate-100 bg-slate-50 px-5 py-3 text-xs font-bold uppercase tracking-[0.08em] text-slate-500 lg:grid"><span>Company</span><span>Role</span><span>Applicants</span><span>Status</span><span>Action</span></div><div className="divide-y divide-slate-100">{drives.map(drive => <article key={drive._id} className="grid gap-3 px-5 py-5 lg:grid-cols-[minmax(12rem,1.3fr)_minmax(12rem,1.3fr)_7rem_7rem_8rem] lg:items-center"><Value label="Company" value={drive.company?.companyName || 'Company'} /><Value label="Role" value={drive.role?.title || 'Placement Drive'} /><Value label="Applicants" value={drive.applicationCount} /><div><p className="text-xs font-bold uppercase tracking-[0.08em] text-slate-500 lg:hidden">Status</p><StatusBadge status="published">Live to Students</StatusBadge></div><Link className={primaryLinkStyle} to={`/admin/placement-drives/${drive._id}/monitoring`}>Manage</Link></article>)}</div></section> }
function SummaryBar({ items }) { return <section className={`grid divide-y overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm sm:grid-cols-2 sm:divide-x sm:divide-y-0 ${items.length === 5 ? 'lg:grid-cols-5' : 'lg:grid-cols-4'}`}>{items.map(([label, value]) => <div key={label} className="px-4 py-4"><p className="text-xs font-bold uppercase tracking-[0.08em] text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-950">{value ?? 0}</p></div>)}</section> }
function Value({ label, value }) { return <div><p className="text-xs font-bold uppercase tracking-[0.08em] text-slate-500 lg:hidden">{label}</p><p className="mt-1 text-sm font-semibold text-slate-800 lg:mt-0">{value === '' || value == null ? 'Not set' : value}</p></div> }
