import { HelpSupportIcon } from '../components/help/HelpSupportIcon.jsx'
import { PageHeader } from '../components/ui/PageHeader.jsx'

const contacts = [
  ['Information Technology', 'Dr. Priya Nair', 'priya.nair@placementhub-demo.edu', 'Aarav Mehta', 'aarav.it@placementhub-demo.edu', '+91 90000 21001', 'Ananya Rao', 'ananya.it@placementhub-demo.edu', '+91 90000 21002'],
  ['Computer Science and Engineering', 'Dr. Vivek Menon', 'vivek.menon@placementhub-demo.edu', 'Aditya Jain', 'aditya.cse@placementhub-demo.edu', '+91 90000 22001', 'Riya Kapoor', 'riya.cse@placementhub-demo.edu', '+91 90000 22002'],
  ['Electronics and Communication Engineering', 'Dr. Kavita Iyer', 'kavita.iyer@placementhub-demo.edu', 'Arjun Patel', 'arjun.ece@placementhub-demo.edu', '+91 90000 23001', 'Sneha Kulkarni', 'sneha.ece@placementhub-demo.edu', '+91 90000 23002'],
  ['Electrical Engineering', 'Dr. Manoj Deshmukh', 'manoj.deshmukh@placementhub-demo.edu', 'Harsh Vardhan', 'harsh.ee@placementhub-demo.edu', '+91 90000 24001', 'Ishita Singh', 'ishita.ee@placementhub-demo.edu', '+91 90000 24002'],
  ['Mechanical Engineering', 'Dr. Rakesh Sinha', 'rakesh.sinha@placementhub-demo.edu', 'Kunal Verma', 'kunal.mech@placementhub-demo.edu', '+91 90000 25001', 'Nisha Agrawal', 'nisha.mech@placementhub-demo.edu', '+91 90000 25002'],
  ['Civil Engineering', 'Dr. Meera Joshi', 'meera.joshi@placementhub-demo.edu', 'Rahul Tiwari', 'rahul.civil@placementhub-demo.edu', '+91 90000 26001', 'Pooja Sharma', 'pooja.civil@placementhub-demo.edu', '+91 90000 26002'],
  ['Chemical Engineering', 'Dr. Nitin Bansal', 'nitin.bansal@placementhub-demo.edu', 'Yash Gupta', 'yash.chem@placementhub-demo.edu', '+91 90000 27001', 'Sakshi Dubey', 'sakshi.chem@placementhub-demo.edu', '+91 90000 27002'],
  ['Biomedical Engineering', 'Dr. Shalini Bose', 'shalini.bose@placementhub-demo.edu', 'Dev Malhotra', 'dev.biomed@placementhub-demo.edu', '+91 90000 28001', 'Aditi Mishra', 'aditi.biomed@placementhub-demo.edu', '+91 90000 28002'],
  ['Biotechnology', 'Dr. Anil Chatterjee', 'anil.chatterjee@placementhub-demo.edu', 'Rohan Das', 'rohan.biotech@placementhub-demo.edu', '+91 90000 29001', 'Tanya Roy', 'tanya.biotech@placementhub-demo.edu', '+91 90000 29002'],
  ['Metallurgical and Materials Engineering', 'Dr. Deepak Rao', 'deepak.rao@placementhub-demo.edu', 'Akash Soni', 'akash.meta@placementhub-demo.edu', '+91 90000 30001', 'Kritika Jain', 'kritika.meta@placementhub-demo.edu', '+91 90000 30002'],
  ['Mining Engineering', 'Dr. Sanjay Pradhan', 'sanjay.pradhan@placementhub-demo.edu', 'Nikhil Yadav', 'nikhil.mining@placementhub-demo.edu', '+91 90000 31001', 'Megha Patel', 'megha.mining@placementhub-demo.edu', '+91 90000 31002'],
].map(([branch, facultyName, facultyEmail, maleName, maleEmail, malePhone, femaleName, femaleEmail, femalePhone]) => ({ branch, faculty: { name: facultyName, email: facultyEmail }, male: { name: maleName, email: maleEmail, phone: malePhone }, female: { name: femaleName, email: femaleEmail, phone: femalePhone } }))

const button = 'inline-flex min-h-10 items-center justify-center rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700 transition hover:border-violet-300 hover:bg-violet-50 hover:text-violet-800'
const whatsapp = phone => `https://wa.me/${phone.replace(/\D/g, '')}`

export function HelpSupportPage() {
  return <section className="space-y-7"><PageHeader eyebrow="PlacementHub directory" title="Help & Support" description="Contact the Placement Cell or your department placement coordinators for placement-related assistance." action={<span className="inline-flex h-11 w-11 items-center justify-center rounded-xl border border-violet-100 bg-violet-50 text-violet-700"><HelpSupportIcon className="h-5 w-5" /></span>} />
    <p className="text-sm text-slate-500">Demo contact directory for the PlacementHub project. Names and contact details are sample information, not official Apex Institute of Technology contacts.</p>
    <section><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-violet-700">Official coordination</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-950">Placement Cell</h2><p className="mt-2 text-sm leading-6 text-slate-600">For placement queries, company coordination, drive-related support, and institutional assistance.</p></div><div className="mt-5 grid gap-4 lg:grid-cols-3"><ContactCard prominent name="Dr. Arvind Sharma" role="Head, Career Development Centre" email="head.placement@placementhub-demo.edu" /><ContactCard name="Placement Office" role="General placement queries, drive coordination, documentation, and official communication." email="placements@placementhub-demo.edu" emailLabel="Email Placement Office" /><ContactCard name="Ms. Neha Verma" role="Placement Executive" email="neha.verma@placementhub-demo.edu" phone="+91 90000 11001" /><ContactCard name="Mr. Rohit Mishra" role="Placement Executive" email="rohit.mishra@placementhub-demo.edu" phone="+91 90000 11002" /></div></section>
    <section><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-violet-700">Branch directory</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-950">Department Coordinators</h2><p className="mt-2 text-sm text-slate-600">Open a branch to find its faculty and student placement coordinators.</p></div><div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{contacts.map((contact, index) => <details key={contact.branch} className="group border-b border-slate-100 last:border-0" open={index === 0}><summary className="flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-4 font-bold text-slate-900 marker:content-none hover:bg-slate-50"><span>{contact.branch}</span><span className="text-violet-700 transition group-open:rotate-45">+</span></summary><div className="grid gap-4 border-t border-slate-100 px-5 py-5 md:grid-cols-3"><Coordinator title="Faculty Coordinator" person={contact.faculty} /><Coordinator title="Male Student Coordinator" person={contact.male} /><Coordinator title="Female Student Coordinator" person={contact.female} /></div></details>)}</div></section>
    <section className="premium-surface p-6"><p className="eyebrow">About Developer</p><h2 className="mt-2 text-xl font-extrabold tracking-tight text-slate-950">Developed by Suryansh Dwivedi</h2><p className="mt-2 text-sm leading-6 text-slate-600">B.Tech Information Technology · PlacementHub — Academic Project</p></section>
  </section>
}

function ContactCard({ prominent, name, role, email, phone, emailLabel = 'Email' }) { return <article className={`rounded-2xl border p-5 shadow-sm ${prominent ? 'border-violet-200 bg-violet-50/70 lg:col-span-1' : 'border-slate-200 bg-white'}`}><h3 className="font-bold text-slate-950">{name}</h3><p className="mt-1 min-h-10 text-sm leading-5 text-slate-600">{role}</p><p className="mt-4 break-all text-sm text-slate-700">{email}</p>{phone && <p className="mt-1 text-sm text-slate-600">{phone}</p>}<div className="mt-4 flex flex-wrap gap-2"><a className={button} href={`mailto:${email}`}>{emailLabel}</a>{phone && <a className={button} href={whatsapp(phone)} target="_blank" rel="noreferrer">WhatsApp</a>}</div></article> }
function Coordinator({ title, person }) { return <article><p className="text-xs font-bold uppercase tracking-[0.1em] text-slate-500">{title}</p><h3 className="mt-2 font-bold text-slate-950">{person.name}</h3><p className="mt-1 break-all text-sm text-slate-600">{person.email}</p>{person.phone && <p className="mt-1 text-sm text-slate-600">{person.phone}</p>}<div className="mt-3 flex flex-wrap gap-2"><a className={button} href={`mailto:${person.email}`}>Email</a>{person.phone && <a className={button} href={whatsapp(person.phone)} target="_blank" rel="noreferrer">WhatsApp</a>}</div></article> }



