import { AppError } from '../../errors/app-error.js'
import { USER_ROLES } from '../auth/auth.constants.js'
import { User } from '../auth/auth.model.js'
import { Company } from './company.model.js'
import { readFile, unlink } from 'node:fs/promises'
const requiredProfileFields = ['companyName','industry','companyType','companySize','location','website','officialEmail','description','recruiterName','recruiterDesignation','recruiterEmail','recruiterPhone','hiringType','recruitmentTimeline','recruitmentMode','expectedHires']
export async function getAdminParticipationLetter(companyUserId, { userModel = User, companyModel = Company } = {}) {
  const user = await userModel.findOne({ _id: companyUserId, role: USER_ROLES.COMPANY }).select('_id')
  if (!user) throw new AppError('Company account was not found.', { statusCode: 404, errorCode: 'NOT_FOUND' })
  return getParticipationLetter(user._id, { companyModel })
}
export const hasCompleteProfile = (company) => requiredProfileFields.every((field) => company[field] !== undefined && company[field] !== '') && Boolean(company.participationLetter) && (company.roleDomains ?? []).length > 0 && (company.targetBranches ?? []).length > 0
export async function ensureCompanyProfile(userId, { companyModel = Company } = {}) { return companyModel.findOneAndUpdate({ userId }, { $setOnInsert: { userId } }, { new: true, upsert: true, setDefaultsOnInsert: true }) }
export async function updateCompanyProfile(userId, input, { companyModel = Company } = {}) { const current=await ensureCompanyProfile(userId,{companyModel}); const material=['companyName','industry','companyType','officialEmail','recruiterName','recruiterEmail','hiringType','targetBranches'].some(k=>JSON.stringify(current[k]??null)!==JSON.stringify(input[k]??null)); const update={...input}; if(current.approvalStatus==='approved'&&material) Object.assign(update,{approvalStatus:'pending',reviewedBy:undefined,reviewedAt:undefined,rejectionReason:undefined}); return companyModel.findOneAndUpdate({ userId }, { $set: update }, { new: true, runValidators: true }) }
export async function uploadParticipationLetter(userId,file,{companyModel=Company}={}) { if(!file) throw new AppError('Attach a PDF participation letter.',{statusCode:422,errorCode:'VALIDATION_ERROR'}); const bytes=await readFile(file.path).catch(()=>null); if(!bytes?.subarray(0,5).equals(Buffer.from('%PDF-'))){await unlink(file.path).catch(()=>{});throw new AppError('The uploaded file is not a valid PDF.',{statusCode:422,errorCode:'VALIDATION_ERROR'})} const company=await ensureCompanyProfile(userId,{companyModel}); const previous=company.participationLetter?.storagePath; company.participationLetter={originalName:file.originalname,storagePath:file.path,mimeType:file.mimetype,size:file.size,uploadedAt:new Date()}; if(company.approvalStatus==='approved'){company.approvalStatus='pending';company.reviewedBy=undefined;company.reviewedAt=undefined;company.rejectionReason=undefined} try{await company.save()}catch(e){await unlink(file.path).catch(()=>{});throw e} if(previous&&previous!==file.path)await unlink(previous).catch(()=>{});return company }
export async function getParticipationLetter(userId,{companyModel=Company}={}) { const company=await ensureCompanyProfile(userId,{companyModel});if(!company.participationLetter)throw new AppError('No participation letter has been uploaded yet.',{statusCode:404,errorCode:'NOT_FOUND'});return company.participationLetter }
export async function resubmitCompany(userId,{companyModel=Company}={}) { const company=await ensureCompanyProfile(userId,{companyModel});if(company.approvalStatus!=='rejected')throw new AppError('Only rejected company profiles can be resubmitted.',{statusCode:409,errorCode:'CONFLICT'});if(!hasCompleteProfile(company))throw new AppError('Complete the required company profile and participation letter before resubmitting.',{statusCode:409,errorCode:'CONFLICT'});company.approvalStatus='pending';company.reviewedBy=undefined;company.reviewedAt=undefined;company.rejectionReason=undefined;await company.save();return company }
export async function listCompaniesForReview({ userModel = User, companyModel = Company } = {}) { const users = await userModel.find({ role: USER_ROLES.COMPANY }).select('_id name email createdAt').lean(); const profiles = await companyModel.find({ userId: { $in: users.map((u) => u._id) } }).lean(); const byId = new Map(profiles.map((p) => [p.userId.toString(), p])); return Promise.all(users.map(async (user) => { const company = byId.get(user._id.toString()) ?? await ensureCompanyProfile(user._id, { companyModel }); return { ...user, company, isProfileComplete: hasCompleteProfile(company) } })) }
export async function reviewCompany(companyUserId, reviewerId, input, { userModel = User, companyModel = Company } = {}) { const user = await userModel.findOne({ _id: companyUserId, role: USER_ROLES.COMPANY }).select('_id'); if (!user) throw new AppError('Company account was not found.', { statusCode: 404, errorCode: 'NOT_FOUND' }); const company = await ensureCompanyProfile(user._id, { companyModel }); if (company.approvalStatus !== 'pending') throw new AppError('Only pending companies can be reviewed.', { statusCode: 409, errorCode: 'CONFLICT' }); if (!hasCompleteProfile(company)) throw new AppError('The company must complete its profile before review.', { statusCode: 409, errorCode: 'CONFLICT' }); company.approvalStatus = input.status; company.reviewedBy = reviewerId; company.reviewedAt = new Date(); company.rejectionReason = input.status === 'rejected' ? input.rejectionReason : undefined; await company.save(); return company }
