import { randomUUID } from 'node:crypto'; import { mkdir } from 'node:fs/promises'; import path from 'node:path'; import { Router } from 'express'; import multer from 'multer'; import { env } from '../../config/env.js'; import { AppError } from '../../errors/app-error.js'
import { validateBody, validateParams } from '../../middleware/validate-request.js'
import { authenticate, authorizeRoles } from '../auth/auth.middleware.js'
import { USER_ROLES } from '../auth/auth.constants.js'
import { getCompanies, getMyCompany, patchCompanyApproval, patchMyCompany, downloadMyParticipationLetter, downloadAdminParticipationLetter, resubmitMyCompany, uploadMyParticipationLetter } from './company.controller.js'
import { companyApprovalSchema, companyIdParamsSchema, companyProfileSchema } from './company.validation.js'
const dir=path.resolve(env.RESUME_UPLOAD_DIR);await mkdir(dir,{recursive:true});const upload=multer({storage:multer.diskStorage({destination:dir,filename:(r,f,c)=>c(null,`${randomUUID()}.pdf`)}),limits:{fileSize:env.RESUME_MAX_FILE_SIZE_BYTES,files:1},fileFilter:(r,f,c)=>f.mimetype==='application/pdf'&&path.extname(f.originalname).toLowerCase()==='.pdf'?c(null,true):c(new AppError('Only PDF files are allowed.',{statusCode:422,errorCode:'VALIDATION_ERROR'}))})
export const companyRouter = Router(); companyRouter.use(authenticate, authorizeRoles(USER_ROLES.COMPANY)); companyRouter.get('/me', getMyCompany); companyRouter.patch('/me', validateBody(companyProfileSchema), patchMyCompany); companyRouter.post('/me/participation-letter',upload.single('letter'),uploadMyParticipationLetter); companyRouter.get('/me/participation-letter/download',downloadMyParticipationLetter);companyRouter.post('/me/approval/resubmit',resubmitMyCompany)
export const adminCompanyRouter = Router(); adminCompanyRouter.use(authenticate, authorizeRoles(USER_ROLES.PLACEMENT_ADMIN)); adminCompanyRouter.get('/', getCompanies); adminCompanyRouter.patch('/:id/approval', validateParams(companyIdParamsSchema), validateBody(companyApprovalSchema), patchCompanyApproval)
adminCompanyRouter.get('/:id/participation-letter/download', validateParams(companyIdParamsSchema), downloadAdminParticipationLetter)
